// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 The Grimoire Authors

//! `grim schema` — emit a JSON Schema for an author-facing TOML format.
//!
//! Generates a JSON Schema (draft 2020-12) from the real `Deserialize`
//! structs — `RawConfig` for `grimoire.toml`, `PublishManifest` for
//! `publish.toml` — via `schemars`, so the published schema can never
//! describe a shape the parser does not accept. The generated document is
//! decorated with the published `$id`, a friendly `title`, and the draft
//! `$schema` keyword, then pretty-printed to stdout.
//!
//! Like `tui`, this command emits a document rather than a `Printable`
//! report, so (per subsystem-cli-api.md "Commands That Exec a Child
//! Process") it is wired directly in `app.rs` without an `api/` report
//! module — the JSON it prints is the payload, not a table.

use std::io::Write;

use clap::{Args, ValueEnum};

use crate::cli::exit_code::ExitCode;
use crate::cli::printer::tag_stdout_pipe;

/// Base URL the published schemas are hosted at (the GitHub Pages docs
/// site). Joined with each kind's filename to form the `$id`.
const SCHEMA_BASE_URL: &str = "https://grimoire.rs/schemas";

/// The JSON Schema draft the generated documents declare via `$schema`.
const SCHEMA_DRAFT: &str = "https://json-schema.org/draft/2020-12/schema";

/// Published filename of the `grimoire.toml` schema.
const CONFIG_SCHEMA_FILE: &str = "grimoire-config.schema.json";

/// Published filename of the `publish.toml` schema.
const PUBLISH_SCHEMA_FILE: &str = "grim-publish.schema.json";

/// Published filename of the `grimoire.lock` schema.
const LOCK_SCHEMA_FILE: &str = "grimoire-lock.schema.json";

/// Published filename of the MCP descriptor (`mcp/<name>.toml`) schema.
const MCP_SCHEMA_FILE: &str = "grim-mcp.schema.json";

/// Which author-facing TOML format to emit a JSON Schema for.
#[derive(Debug, Clone, Copy, PartialEq, Eq, ValueEnum)]
pub enum SchemaKind {
    /// The `grimoire.toml` declaration file (project and global scope share
    /// the same shape).
    Config,
    /// The `publish.toml` batch-release manifest.
    Publish,
    /// The `grimoire.lock` lockfile (generated by grim, but published so
    /// tooling can validate or introspect it).
    Lock,
    /// The MCP server descriptor (`mcp/<name>.toml`).
    Mcp,
}

/// `grim schema` arguments.
#[derive(Debug, Args)]
pub struct SchemaArgs {
    /// The TOML format to emit a JSON Schema for.
    #[arg(long)]
    pub kind: SchemaKind,
}

impl SchemaKind {
    /// The published `$id` URL for this kind's schema.
    fn id(self) -> String {
        let file = match self {
            SchemaKind::Config => CONFIG_SCHEMA_FILE,
            SchemaKind::Publish => PUBLISH_SCHEMA_FILE,
            SchemaKind::Lock => LOCK_SCHEMA_FILE,
            SchemaKind::Mcp => MCP_SCHEMA_FILE,
        };
        format!("{SCHEMA_BASE_URL}/{file}")
    }

    /// The human-facing schema `title`.
    fn title(self) -> &'static str {
        match self {
            SchemaKind::Config => "grimoire.toml — Grimoire declaration file",
            SchemaKind::Publish => "publish.toml — Grimoire publish manifest",
            SchemaKind::Lock => "grimoire.lock — Grimoire lockfile",
            SchemaKind::Mcp => "mcp/<name>.toml — Grimoire MCP server descriptor",
        }
    }
}

/// The published `$id` URL of the `grimoire.toml` schema — the value
/// `grim init` seeds as the `#:schema` editor directive. Single-sourced
/// here so the directive can never drift from the published schema.
pub fn config_schema_id() -> String {
    SchemaKind::Config.id()
}

/// Generate the decorated JSON Schema document for `kind`.
///
/// Pure and unit-testable: builds the schema from the real parse struct,
/// injects `$schema`/`$id`/`title`, and pretty-prints. No trailing newline
/// — the caller adds one.
///
/// # Errors
///
/// Returns an error only if the generated schema fails to serialize — an
/// unreachable case for these fixed, derive-generated structs, surfaced as
/// a `Result` rather than a panic so the command path stays panic-free.
pub fn generate(kind: SchemaKind) -> anyhow::Result<String> {
    let schema = match kind {
        SchemaKind::Config => crate::config::project_config::config_json_schema(),
        SchemaKind::Publish => schemars::schema_for!(crate::command::publish::PublishManifest),
        SchemaKind::Lock => crate::lock::grimoire_lock::lock_json_schema(),
        SchemaKind::Mcp => schemars::schema_for!(crate::oci::mcp::McpDescriptor),
    };
    decorate(&schema, &kind.id(), kind.title())
}

/// Inject the published `$id`, friendly `title`, and the draft `$schema`
/// keyword into a generated schema, then pretty-print it.
///
/// Works on the serialized `serde_json::Value` (rather than `schemars`
/// mutators) so the decoration uses only stable serde_json APIs; `schemars`
/// already emits a draft-2020-12 `$schema` and a type-name `title`, both of
/// which this overwrites with the published values.
fn decorate(schema: &schemars::Schema, id: &str, title: &str) -> anyhow::Result<String> {
    let mut value = serde_json::to_value(schema)?;
    let obj = value
        .as_object_mut()
        .ok_or_else(|| anyhow::anyhow!("generated JSON Schema is not an object"))?;
    obj.insert(
        "$schema".to_string(),
        serde_json::Value::String(SCHEMA_DRAFT.to_string()),
    );
    obj.insert("$id".to_string(), serde_json::Value::String(id.to_string()));
    obj.insert("title".to_string(), serde_json::Value::String(title.to_string()));
    Ok(serde_json::to_string_pretty(&value)?)
}

/// Run `grim schema`: print the JSON Schema for the requested kind to
/// stdout, followed by a trailing newline.
///
/// # Errors
///
/// Propagates a schema-serialization failure from [`generate`] (unreachable
/// in practice), or a broken-pipe-tagged error when writing to stdout fails
/// (e.g. the downstream reader of `grim schema … | head` closed the pipe).
pub fn run(args: &SchemaArgs) -> anyhow::Result<ExitCode> {
    let json = generate(args.kind)?;
    writeln!(std::io::stdout(), "{json}").map_err(tag_stdout_pipe)?;
    Ok(ExitCode::Success)
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Parse a kind's generated schema into a JSON value for inspection.
    fn parsed(kind: SchemaKind) -> serde_json::Value {
        serde_json::from_str(&generate(kind).expect("schema generates")).expect("generated schema is valid JSON")
    }

    #[test]
    fn config_schema_carries_id_title_draft_and_strict_object() {
        let v = parsed(SchemaKind::Config);
        assert_eq!(v["$id"], "https://grimoire.rs/schemas/grimoire-config.schema.json");
        assert_eq!(v["$schema"], SCHEMA_DRAFT);
        assert_eq!(v["title"], "grimoire.toml — Grimoire declaration file");
        // `deny_unknown_fields` on RawConfig ⇒ additionalProperties:false, so
        // an editor flags a typo'd table key instead of silently dropping it.
        assert_eq!(v["additionalProperties"], serde_json::Value::Bool(false));
    }

    #[test]
    fn mcp_schema_carries_id_title_and_covers_server_and_oauth() {
        let v = parsed(SchemaKind::Mcp);
        assert_eq!(v["$id"], "https://grimoire.rs/schemas/grim-mcp.schema.json");
        assert_eq!(v["$schema"], SCHEMA_DRAFT);
        assert_eq!(v["title"], "mcp/<name>.toml — Grimoire MCP server descriptor");
        assert_eq!(v["additionalProperties"], serde_json::Value::Bool(false));
        let required = v["required"].as_array().expect("required is an array");
        assert!(required.iter().any(|r| r == "description"));
        assert!(required.iter().any(|r| r == "server"));
        // Struct-derived: the transport enum and oauth block ride along
        // automatically, so schema output tracks descriptor growth.
        let defs = v["$defs"].as_object().expect("$defs object");
        assert!(defs.contains_key("McpTransport"), "{defs:?}");
        assert!(defs.contains_key("McpOAuth"), "{defs:?}");
    }

    #[test]
    fn publish_schema_carries_id_title_and_requires_registry() {
        let v = parsed(SchemaKind::Publish);
        assert_eq!(v["$id"], "https://grimoire.rs/schemas/grim-publish.schema.json");
        assert_eq!(v["$schema"], SCHEMA_DRAFT);
        assert_eq!(v["title"], "publish.toml — Grimoire publish manifest");
        assert_eq!(v["additionalProperties"], serde_json::Value::Bool(false));
        // `registry` is the one required top-level field.
        let required = v["required"].as_array().expect("required is an array");
        assert!(
            required.iter().any(|r| r == "registry"),
            "publish schema must require `registry`, got: {required:?}"
        );
    }

    #[test]
    fn publish_schema_repository_fields_are_optional() {
        // Axis B (issue #11): `repository_prefix` (manifest) and `repository`
        // (per-entry) are additive optional fields — `registry` stays the only
        // required top-level field, and both new fields appear in the schema.
        let v = parsed(SchemaKind::Publish);
        let required = v["required"].as_array().expect("required is an array");
        assert_eq!(
            required.len(),
            1,
            "`registry` must remain the only required top-level field, got: {required:?}"
        );
        assert_eq!(required[0], "registry");
        assert!(
            v["properties"]["repository_prefix"].is_object(),
            "repository_prefix must be a documented manifest property"
        );
        let entry = v["$defs"]["PublishEntrySpec"]
            .as_object()
            .expect("PublishEntrySpec definition present");
        assert!(
            entry["properties"]["repository"].is_object(),
            "per-entry repository must be a documented property"
        );
        // Since issue #29 the entry `version` is optional too, so the entry
        // has NO required fields — schemars omits the `required` array
        // entirely (or, defensively, an array without `repository`/`version`).
        if let Some(entry_required) = entry.get("required").and_then(|r| r.as_array()) {
            assert!(
                !entry_required.iter().any(|r| r == "repository" || r == "version"),
                "per-entry repository and version must be optional, got: {entry_required:?}"
            );
        }
    }

    #[test]
    fn publish_schema_documents_description_companion_fields() {
        // The description companion adds an optional top-level `[description]`
        // table and an optional per-entry `description` — `registry` must stay
        // the only required top-level field.
        let v = parsed(SchemaKind::Publish);
        assert!(
            v["properties"]["description"].is_object(),
            "top-level description must be a documented manifest property"
        );
        let required = v["required"].as_array().expect("required is an array");
        assert_eq!(required.len(), 1, "only `registry` required, got: {required:?}");
        assert_eq!(required[0], "registry");
        // Per-entry `description` is a documented (optional) entry property.
        let entry = v["$defs"]["PublishEntrySpec"]
            .as_object()
            .expect("PublishEntrySpec definition present");
        assert!(
            entry["properties"]["description"].is_object(),
            "per-entry description must be a documented property"
        );
        // The DescriptionSpec definition documents the well-known members.
        let spec = v["$defs"]["DescriptionSpec"]
            .as_object()
            .expect("DescriptionSpec definition present");
        for key in ["readme", "logo", "changelog", "include", "publish"] {
            assert!(
                spec["properties"][key].is_object(),
                "DescriptionSpec must document `{key}`"
            );
        }
    }

    #[test]
    fn publish_schema_documents_catalog_wide_version() {
        // Issue #29: the top-level `version` / `version_prefix` are documented
        // optional manifest properties; `registry` stays the only required one.
        let v = parsed(SchemaKind::Publish);
        assert!(
            v["properties"]["version"].is_object(),
            "top-level version must be a documented manifest property"
        );
        assert!(
            v["properties"]["version_prefix"].is_object(),
            "version_prefix must be a documented manifest property"
        );
        let required = v["required"].as_array().expect("required is an array");
        assert_eq!(required.len(), 1, "only `registry` required, got: {required:?}");
    }

    #[test]
    fn lock_schema_carries_id_title_draft_and_strict_object() {
        let v = parsed(SchemaKind::Lock);
        assert_eq!(v["$id"], "https://grimoire.rs/schemas/grimoire-lock.schema.json");
        assert_eq!(v["$schema"], SCHEMA_DRAFT);
        assert_eq!(v["title"], "grimoire.lock — Grimoire lockfile");
        // `deny_unknown_fields` on RawLock ⇒ additionalProperties:false.
        assert_eq!(v["additionalProperties"], serde_json::Value::Bool(false));
        // `metadata` is the one required top-level table.
        let required = v["required"].as_array().expect("required is an array");
        assert_eq!(required.len(), 1, "only `metadata` required, got: {required:?}");
        assert_eq!(required[0], "metadata");
    }

    #[test]
    fn lock_schema_describes_wire_shapes() {
        let v = parsed(SchemaKind::Lock);
        // lock_version is a bare-integer enum, not a string enum of
        // variant names (manual JsonSchema on LockVersion).
        let version = &v["$defs"]["LockVersion"];
        assert_eq!(version["type"], "integer");
        assert_eq!(version["enum"], serde_json::json!([1]));
        // pinned is a digest-bearing string (manual JsonSchema on
        // PinnedIdentifier), not an object of private fields.
        let pinned = &v["$defs"]["PinnedIdentifier"];
        assert_eq!(pinned["type"], "string");
        assert!(
            pinned["pattern"].as_str().unwrap().contains("sha256"),
            "pinned pattern anchors on the digest: {pinned}"
        );
        // The artifact entry describes the raw wire shape incl. both
        // provenance forms.
        let entry = v["$defs"]["LockedArtifact"].as_object().expect("entry def");
        for key in ["name", "pinned", "bundle", "bundle_tag", "bundles"] {
            assert!(
                entry["properties"][key].is_object() || entry["properties"][key].is_boolean(),
                "lock entry must document `{key}`"
            );
        }
        // The bundle cache section round-trips through the real structs.
        assert!(v["$defs"]["LockedBundle"].is_object());
        assert!(v["$defs"]["BundleMember"].is_object());
    }

    #[test]
    fn each_kind_emits_a_distinct_id() {
        assert_ne!(SchemaKind::Config.id(), SchemaKind::Publish.id());
        assert_ne!(SchemaKind::Config.id(), SchemaKind::Lock.id());
        assert_ne!(SchemaKind::Publish.id(), SchemaKind::Lock.id());
    }
}
