// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 The Grimoire Authors

//! The client-transform seam: turn a materialized canonical artifact tree
//! into the on-disk layout one client expects.
//!
//! **Skills**: every client copies the tree verbatim, except `SKILL.md`
//! when it carries tool-namespaced metadata (`claude.<field>: "…"`): then
//! the index is projected per client via [`super::render`] — Claude gets
//! the native typed fields lifted to the top level; OpenCode/Copilot get
//! a clean universal frontmatter with the tool keys removed.
//!
//! **Rules**: Claude copies the index verbatim (`paths:` is native).
//! OpenCode rewrites it to provenance + body — OpenCode has no per-file
//! path scoping; the file is loaded via the managed `instructions` entry
//! in `opencode.json` (see `opencode_config`). Copilot rewrites it to a
//! `<name>.instructions.md` whose frontmatter maps `paths` → `applyTo`
//! (comma-joined) and `copilot.exclude-agent` → `excludeAgent`.
//!
//! Every transform is deterministic — regenerating the same artifact at
//! the same pinned identifier yields byte-identical output, so a user
//! edit to a generated file is detected as drift exactly like a canonical
//! file (the installer hashes the *expected* generated bytes, not the
//! input).

use std::path::{Path, PathBuf};

use crate::config::scope::ConfigScope;
use crate::oci::ArtifactKind;
use crate::skill::{AgentFrontmatter, RuleFrontmatter};

use super::install_error::{InstallError, InstallErrorKind};

use super::vendor::Vendor;
use super::vendor_amp::AmpVendor;
use super::vendor_claude::ClaudeVendor;
use super::vendor_codex::CodexVendor;
use super::vendor_copilot::CopilotVendor;
use super::vendor_cursor::CursorVendor;
use super::vendor_gemini::GeminiVendor;
use super::vendor_junie::JunieVendor;
use super::vendor_kiro::KiroVendor;
use super::vendor_opencode::OpenCodeVendor;
use super::vendor_zed::ZedVendor;

/// A supported client target.
///
/// Closed internal enum (the binary is the only consumer); `Default` is
/// [`ClientTarget::Claude`].
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub enum ClientTarget {
    /// Claude Code — `.claude/{skills,rules}`.
    #[default]
    Claude,
    /// OpenCode — `.opencode/{skills,rules}`.
    OpenCode,
    /// GitHub Copilot — `.github/{skills,instructions}` (rules transformed).
    Copilot,
    /// OpenAI Codex — `.agents/skills` + `.codex/agents/<name>.toml`
    /// (skills + agents only; rules unsupported).
    Codex,
    /// Cursor — `.cursor/{skills,rules,agents,mcp.json}` (all four kinds
    /// native; rules render to `.mdc`).
    Cursor,
    /// Kiro (AWS) — `.kiro/{skills,steering,settings/mcp.json}` (skills,
    /// rules, MCP; agents declined — CLI/IDE schema collision).
    Kiro,
    /// JetBrains Junie — `.junie/{skills,mcp/mcp.json}` (skills + MCP;
    /// rules and agents declined — no ownable per-file surface / EAP-only).
    Junie,
    /// Gemini CLI — shared `.agents/skills` + `.gemini/{agents,settings.json}`
    /// (skills, agents, MCP; rules declined — GEMINI.md hierarchy only).
    Gemini,
    /// Zed — shared `.agents/skills` + `.zed/settings.json` (skills + MCP;
    /// rules and agents declined — no scoping / ACP-only agents).
    Zed,
    /// Amp — shared `.agents/skills` + `.amp/settings.json` (skills + MCP;
    /// rules and agents declined — AGENTS.md only / runtime subagents).
    Amp,
}

impl std::str::FromStr for ClientTarget {
    type Err = InstallError;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s {
            "claude" => Ok(Self::Claude),
            "opencode" => Ok(Self::OpenCode),
            "copilot" => Ok(Self::Copilot),
            "codex" => Ok(Self::Codex),
            "cursor" => Ok(Self::Cursor),
            "kiro" => Ok(Self::Kiro),
            "junie" => Ok(Self::Junie),
            "gemini" => Ok(Self::Gemini),
            "zed" => Ok(Self::Zed),
            "amp" => Ok(Self::Amp),
            other => Err(InstallError::without_reference(InstallErrorKind::UnsupportedClient(
                other.to_string(),
            ))),
        }
    }
}

impl std::fmt::Display for ClientTarget {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(self.as_str())
    }
}

impl ClientTarget {
    /// The canonical lowercase name for this client (`claude` / `opencode` /
    /// `copilot` / `codex`). Zero-alloc form of [`Display`]; round-trips
    /// through [`std::str::FromStr`]. Used to compare against the stored
    /// [`super::install_state::ClientOutput::client`] string without an
    /// intermediate allocation.
    pub const fn as_str(&self) -> &'static str {
        match self {
            Self::Claude => "claude",
            Self::OpenCode => "opencode",
            Self::Copilot => "copilot",
            Self::Codex => "codex",
            Self::Cursor => "cursor",
            Self::Kiro => "kiro",
            Self::Junie => "junie",
            Self::Gemini => "gemini",
            Self::Zed => "zed",
            Self::Amp => "amp",
        }
    }

    /// The stable lowercase identifier for each variant, in declaration
    /// order — the single list `command::config_keys` presents as the
    /// `options.clients` config key's allowed values (mirrors
    /// [`crate::config::declaration::DefaultView::VALUE_NAMES`]).
    pub const VALUE_NAMES: &'static [&'static str] = &[
        Self::Claude.as_str(),
        Self::OpenCode.as_str(),
        Self::Copilot.as_str(),
        Self::Codex.as_str(),
        Self::Cursor.as_str(),
        Self::Kiro.as_str(),
        Self::Junie.as_str(),
        Self::Gemini.as_str(),
        Self::Zed.as_str(),
        Self::Amp.as_str(),
    ];
}

/// One file produced for an client target.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct MaterializedFile {
    /// The absolute on-disk path written.
    pub path: PathBuf,
    /// Whether the file is a generated transform (vs. a canonical copy).
    /// Generated files are integrity-hashed against their *expected*
    /// bytes so a user edit is still detected as drift.
    pub generated: bool,
}

/// The inputs to [`ClientTarget::materialize`]: what to materialize, from
/// where, and to where. Bundled into one struct so the entry point stays a
/// two-argument call and each field is named at the call site.
#[derive(Debug, Clone, Copy)]
pub struct MaterializeRequest<'a> {
    /// The artifact kind (skill / rule / agent).
    pub kind: ArtifactKind,
    /// The binding name (may differ from the canonical frontmatter name).
    pub name: &'a str,
    /// The extracted canonical content root: the skill directory
    /// (`<name>/…`) or the rule / agent index file (`<name>.md`).
    pub artifact_root: &'a Path,
    /// The final on-disk destination from [`ClientTarget::path_for`].
    pub dest: &'a Path,
    /// The install scope.
    pub scope: ConfigScope,
    /// The pinned identifier stamped into generated-file provenance.
    pub pinned: &'a str,
    /// The optional sibling support directory of a multi-file rule.
    pub support_dir: Option<&'a Path>,
}

impl ClientTarget {
    /// Every supported client, in canonical order.
    pub const ALL: [ClientTarget; 10] = [
        Self::Claude,
        Self::OpenCode,
        Self::Copilot,
        Self::Codex,
        Self::Cursor,
        Self::Kiro,
        Self::Junie,
        Self::Gemini,
        Self::Zed,
        Self::Amp,
    ];

    /// The per-vendor materialization strategy behind this identity.
    pub fn vendor(self) -> &'static dyn Vendor {
        match self {
            Self::Claude => &ClaudeVendor,
            Self::OpenCode => &OpenCodeVendor,
            Self::Copilot => &CopilotVendor,
            Self::Codex => &CodexVendor,
            Self::Cursor => &CursorVendor,
            Self::Kiro => &KiroVendor,
            Self::Junie => &JunieVendor,
            Self::Gemini => &GeminiVendor,
            Self::Zed => &ZedVendor,
            Self::Amp => &AmpVendor,
        }
    }

    /// The absolute install path for the named artifact of `kind` under
    /// `workspace` at `scope`. A skill installs as a directory; a rule as
    /// a single file. Project scope lands under `<workspace>/<root_dir>`;
    /// global scope lands in the vendor's native user-level discovery
    /// location (see [`Vendor::skills_root`] / [`Vendor::rule_path`]).
    pub fn path_for(
        self,
        workspace: &Path,
        scope: crate::config::scope::ConfigScope,
        kind: ArtifactKind,
        name: &str,
    ) -> PathBuf {
        match kind {
            ArtifactKind::Skill => self.vendor().skills_root(workspace, scope).join(name),
            ArtifactKind::Rule => self.vendor().rule_path(workspace, scope, name),
            ArtifactKind::Agent => self.vendor().agent_path(workspace, scope, name),
            // An MCP descriptor registers into the vendor's MCP config file
            // (no file of its own); the config path is the reportable
            // target. The workspace-conventional `.mcp.json` stands in when
            // the vendor has no surface for this scope (report-only — the
            // install itself skips such a vendor).
            ArtifactKind::Mcp => self
                .vendor()
                .mcp_config_path(workspace, scope)
                .unwrap_or_else(|| workspace.join(".mcp.json")),
            // Bundles never materialize; they expand into members.
            ArtifactKind::Bundle => unreachable!("bundles are never materialized; they expand into members"),
        }
    }

    /// Materialize the canonical artifact tree at `artifact_root` into the
    /// client layout at `dest`.
    ///
    /// `artifact_root` is the extracted canonical content: the skill
    /// directory (`<name>/…`) or the rule index file (`<name>.md`). `dest`
    /// is the final path from [`Self::path_for`]. For a skill, the tree is
    /// copied verbatim. For a rule, Claude/OpenCode copy the index verbatim;
    /// Copilot transforms it (strip `paths:`, prepend provenance header).
    ///
    /// `support_dir` is the optional sibling support directory of a
    /// multi-file rule (`<root>/<name>/`). When present it is copied
    /// verbatim — for every client, including Copilot — beside the index at
    /// `<dest_parent>/<name>/`, so the index's relative links resolve. Only
    /// the index is ever transformed.
    ///
    /// # Errors
    ///
    /// [`InstallErrorKind::TargetIo`] for a filesystem failure;
    /// [`InstallErrorKind::MaterializeFailed`] for an unreadable rule.
    pub fn materialize(self, req: MaterializeRequest<'_>) -> Result<Vec<MaterializedFile>, InstallError> {
        let MaterializeRequest {
            kind,
            name,
            artifact_root,
            dest,
            scope,
            pinned,
            support_dir,
        } = req;
        match kind {
            ArtifactKind::Skill => self.materialize_skill(name, artifact_root, dest),
            ArtifactKind::Rule => self.materialize_rule(name, artifact_root, dest, scope, pinned, support_dir),
            ArtifactKind::Agent => self.materialize_agent(artifact_root, dest, pinned),
            // Bundles never materialize; they expand into members.
            ArtifactKind::Bundle => unreachable!("bundles are never materialized; they expand into members"),
            // MCP descriptors register into client configs; the installer
            // diverges before the materialization path.
            ArtifactKind::Mcp => unreachable!("mcp descriptors register into client configs, never materialize"),
        }
    }

    /// Copy a skill tree into `dest`. Every file copies verbatim except
    /// `SKILL.md` when it carries tool-namespaced metadata: that index is
    /// rendered per client (and marked `generated`, so the integrity hash
    /// anchors on the *expected rendered* bytes). A `--name` rebinding
    /// (binding `name` ≠ frontmatter name) rewrites the frontmatter
    /// `name` to the binding first — the Agent Skills directory-equality
    /// rule must hold at the destination — and that index is generated
    /// even for a vendor that would otherwise copy verbatim. A plain
    /// skill under its own name — or a `SKILL.md` that does not parse —
    /// installs byte-identical to the canonical tree, preserving the
    /// historical verbatim contract.
    fn materialize_skill(
        self,
        name: &str,
        artifact_root: &Path,
        dest: &Path,
    ) -> Result<Vec<MaterializedFile>, InstallError> {
        let mut out = Vec::new();
        copy_tree(artifact_root, dest, &mut out)?;

        let index_src = artifact_root.join("SKILL.md");
        if index_src.is_file() {
            let doc_bytes = std::fs::read(&index_src).map_err(|e| target_io(&index_src, e))?;
            let doc = String::from_utf8_lossy(&doc_bytes);
            // Rebind BEFORE the vendor render so every vendor projects
            // from the corrected document.
            let rebound = super::render::rebind_skill_name(&doc, name);
            let effective = rebound.as_deref().unwrap_or(&doc);
            let rendered = self
                .vendor()
                .skill_index(effective)
                .map_err(|e| materialize_failed(e.to_string()))?;
            let generated_doc = match rendered {
                Some(rendered) => {
                    for warning in &rendered.warnings {
                        tracing::warn!("{warning}");
                    }
                    Some(rendered.document)
                }
                // No vendor transform — but a rebound index is still a
                // generated file, never the canonical bytes.
                None => rebound,
            };
            if let Some(text) = generated_doc {
                let index_dest = dest.join("SKILL.md");
                std::fs::write(&index_dest, text.as_bytes()).map_err(|e| target_io(&index_dest, e))?;
                for file in &mut out {
                    if file.path == index_dest {
                        file.generated = true;
                    }
                }
            }
        }

        out.sort_by(|a, b| a.path.cmp(&b.path));
        Ok(out)
    }

    /// Materialize a rule: the index goes through the vendor's
    /// [`Vendor::rule_index`] transform (`None` ⇒ verbatim copy); an
    /// optional support directory is copied verbatim beside the index for
    /// every client.
    fn materialize_rule(
        self,
        name: &str,
        artifact_root: &Path,
        dest: &Path,
        scope: ConfigScope,
        pinned: &str,
        support_dir: Option<&Path>,
    ) -> Result<Vec<MaterializedFile>, InstallError> {
        let bytes = std::fs::read(artifact_root).map_err(|e| target_io(artifact_root, e))?;
        if let Some(parent) = dest.parent() {
            std::fs::create_dir_all(parent).map_err(|e| target_io(parent, e))?;
        }

        let doc = String::from_utf8_lossy(&bytes);
        let parsed = RuleFrontmatter::parse_doc(&doc, artifact_root).map_err(|e| materialize_failed(e.to_string()))?;
        let rendered = self
            .vendor()
            .rule_index(&parsed, scope, pinned)
            .map_err(|e| materialize_failed(e.to_string()))?;

        let mut out = match rendered {
            // Canonical bytes are what this vendor reads — verbatim copy.
            None => {
                std::fs::write(dest, &bytes).map_err(|e| target_io(dest, e))?;
                vec![MaterializedFile {
                    path: dest.to_path_buf(),
                    generated: false,
                }]
            }
            Some(rendered) => {
                for warning in &rendered.warnings {
                    tracing::warn!("{warning}");
                }
                std::fs::write(dest, rendered.document.as_bytes()).map_err(|e| target_io(dest, e))?;
                vec![MaterializedFile {
                    path: dest.to_path_buf(),
                    generated: true,
                }]
            }
        };

        // Copy the sibling support tree verbatim (all clients, no transform)
        // beside the index at `<dest_parent>/<name>/`, so the index's
        // relative links resolve.
        if let Some(src) = support_dir
            && let Some(parent) = dest.parent()
        {
            copy_tree(src, &parent.join(name), &mut out)?;
        }

        out.sort_by(|a, b| a.path.cmp(&b.path));
        Ok(out)
    }

    /// Materialize an agent: the single file goes through the vendor's
    /// [`Vendor::agent_index`] transform (`None` ⇒ verbatim copy). Agents
    /// have no support directory. An unparseable agent document is a
    /// materialize failure — unlike a rule, the frontmatter is required.
    fn materialize_agent(
        self,
        artifact_root: &Path,
        dest: &Path,
        pinned: &str,
    ) -> Result<Vec<MaterializedFile>, InstallError> {
        let bytes = std::fs::read(artifact_root).map_err(|e| target_io(artifact_root, e))?;
        if let Some(parent) = dest.parent() {
            std::fs::create_dir_all(parent).map_err(|e| target_io(parent, e))?;
        }

        let doc = String::from_utf8_lossy(&bytes);
        let parsed = AgentFrontmatter::parse_doc(&doc, artifact_root).map_err(|e| materialize_failed(e.to_string()))?;
        let rendered = self
            .vendor()
            .agent_index(&parsed, pinned)
            .map_err(|e| materialize_failed(e.to_string()))?;

        let out = match rendered {
            // Canonical bytes are what this vendor reads — verbatim copy.
            None => {
                std::fs::write(dest, &bytes).map_err(|e| target_io(dest, e))?;
                vec![MaterializedFile {
                    path: dest.to_path_buf(),
                    generated: false,
                }]
            }
            Some(rendered) => {
                for warning in &rendered.warnings {
                    tracing::warn!("{warning}");
                }
                std::fs::write(dest, rendered.document.as_bytes()).map_err(|e| target_io(dest, e))?;
                vec![MaterializedFile {
                    path: dest.to_path_buf(),
                    generated: true,
                }]
            }
        };
        Ok(out)
    }
}

fn materialize_failed(msg: String) -> InstallError {
    InstallError::without_reference(InstallErrorKind::MaterializeFailed(msg))
}

/// Recursively copy every regular file under `src` into `dst`, preserving
/// the relative structure. Records each written file as a canonical
/// (non-generated) [`MaterializedFile`].
fn copy_tree(src: &Path, dst: &Path, out: &mut Vec<MaterializedFile>) -> Result<(), InstallError> {
    let meta = std::fs::symlink_metadata(src).map_err(|e| target_io(src, e))?;
    if meta.is_dir() {
        std::fs::create_dir_all(dst).map_err(|e| target_io(dst, e))?;
        let mut children: Vec<PathBuf> = std::fs::read_dir(src)
            .map_err(|e| target_io(src, e))?
            .map(|e| e.map(|e| e.path()))
            .collect::<std::io::Result<Vec<_>>>()
            .map_err(|e| target_io(src, e))?;
        children.sort();
        for child in children {
            let name = child.file_name().unwrap_or_default();
            copy_tree(&child, &dst.join(name), out)?;
        }
    } else if meta.is_file() {
        if let Some(parent) = dst.parent() {
            std::fs::create_dir_all(parent).map_err(|e| target_io(parent, e))?;
        }
        std::fs::copy(src, dst).map_err(|e| target_io(dst, e))?;
        out.push(MaterializedFile {
            path: dst.to_path_buf(),
            generated: false,
        });
    }
    Ok(())
}

fn target_io(path: &Path, source: std::io::Error) -> InstallError {
    InstallError::without_reference(InstallErrorKind::TargetIo {
        path: path.to_path_buf(),
        source,
    })
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::config::scope::ConfigScope;
    use std::str::FromStr;

    #[test]
    fn value_names_match_all_and_round_trip() {
        assert_eq!(ClientTarget::VALUE_NAMES.len(), ClientTarget::ALL.len());
        for (name, target) in ClientTarget::VALUE_NAMES.iter().zip(ClientTarget::ALL) {
            assert_eq!(ClientTarget::from_str(name).unwrap(), target);
        }
    }

    // ── kind_support grid + G4 parity tests (adr_client_compat_matrix) ──

    /// Full 10-vendor × kind grid asserted against the `adr_vendor_wave_expansion`
    /// §1 mapping table: Skill/Rule/Agent via [`Vendor::kind_support`], MCP via
    /// the boolean [`Vendor::mcp_config_path`] surface.
    #[test]
    fn kind_support_grid_matches_adr_mapping_table() {
        use crate::install::vendor::KindSupport::{Declined, Degraded, Native};
        // (client, Skill, Rule, Agent). Every wave-1 vendor also exposes an
        // MCP config surface (asserted below).
        let grid = [
            (ClientTarget::Claude, Native, Native, Native),
            (ClientTarget::OpenCode, Native, Degraded, Native),
            (ClientTarget::Copilot, Native, Native, Native),
            (ClientTarget::Codex, Native, Declined, Native),
            (ClientTarget::Cursor, Native, Native, Native),
            (ClientTarget::Kiro, Native, Native, Declined),
            (ClientTarget::Junie, Native, Declined, Declined),
            (ClientTarget::Gemini, Native, Declined, Native),
            (ClientTarget::Zed, Native, Declined, Declined),
            (ClientTarget::Amp, Native, Declined, Declined),
        ];
        assert_eq!(
            grid.len(),
            ClientTarget::ALL.len(),
            "grid must cover every ClientTarget"
        );
        let project = crate::config::scope::ConfigScope::Project;
        for (client, skill, rule, agent) in grid {
            let v = client.vendor();
            assert_eq!(v.kind_support(ArtifactKind::Skill), skill, "{client} skill");
            assert_eq!(v.kind_support(ArtifactKind::Rule), rule, "{client} rule");
            assert_eq!(v.kind_support(ArtifactKind::Agent), agent, "{client} agent");
            assert!(
                v.mcp_config_path(Path::new("/w"), project).is_some(),
                "{client} must expose an MCP config surface"
            );
        }
    }

    /// A documented support-matrix cell.
    #[derive(PartialEq, Eq, Clone, Copy, Debug)]
    enum Cell {
        Yes,     // ✓
        Partial, // ◐
        No,      // ✗
    }

    /// Parse the first markdown table of a docs page into `(client, [Skill,
    /// Rule, Agent, MCP])` rows. Cell parsing keys on the `✓`/`◐`/`✗` token
    /// only, whitespace- and formatting-insensitive; an unrecognized cell
    /// (e.g. a `TODO` placeholder) is a `None` that fails the caller's assert.
    fn parse_first_matrix(md: &str) -> Vec<(String, [Option<Cell>; 4])> {
        let mut rows = Vec::new();
        let mut in_table = false;
        for line in md.lines() {
            let line = line.trim();
            if !line.starts_with('|') {
                if in_table {
                    break; // table ended
                }
                continue;
            }
            in_table = true;
            let cells: Vec<&str> = line.trim_matches('|').split('|').map(str::trim).collect();
            // Separator row (|----|----|).
            if cells
                .iter()
                .all(|c| !c.is_empty() && c.chars().all(|ch| ch == '-' || ch == ':'))
            {
                continue;
            }
            // Header row (first cell is the literal "Client").
            if cells.first().is_some_and(|c| c.eq_ignore_ascii_case("Client")) {
                continue;
            }
            if cells.len() < 5 {
                continue;
            }
            // The client cell may be a hyperlink (`[Claude]`, `[Claude][claude]`,
            // or `[Claude](url)`) — reduce it to the link text before matching.
            let raw = cells[0];
            let name = raw
                .strip_prefix('[')
                .and_then(|r| r.split_once(']'))
                .map_or(raw, |(text, _)| text)
                .to_ascii_lowercase();
            let cell = |c: &str| {
                if c.contains('✓') {
                    Some(Cell::Yes)
                } else if c.contains('◐') {
                    Some(Cell::Partial)
                } else if c.contains('✗') {
                    Some(Cell::No)
                } else {
                    None
                }
            };
            rows.push((name, [cell(cells[1]), cell(cells[2]), cell(cells[3]), cell(cells[4])]));
        }
        rows
    }

    /// Table-parity: reads `docs/src/clients.md` at compile time, parses the
    /// first markdown table, and asserts for every `(client, kind)` that a
    /// documented `✗` ⇔ `kind_support == Declined` (MCP: `mcp_config_path` is
    /// `None`), `◐` ⇔ `Degraded` (rule column), `✓` ⇔ `Native`, and the row
    /// set equals `ClientTarget::ALL` exactly.
    #[test]
    fn docs_matrix_row_set_matches_all_and_cells_track_kind_support() {
        use crate::install::vendor::KindSupport;
        let md = std::fs::read_to_string(concat!(env!("CARGO_MANIFEST_DIR"), "/docs/src/clients.md"))
            .expect("docs/src/clients.md exists (matrix parity)");
        let rows = parse_first_matrix(&md);

        let documented: std::collections::BTreeSet<&str> = rows.iter().map(|(n, _)| n.as_str()).collect();
        let expected: std::collections::BTreeSet<&str> = ClientTarget::ALL.iter().map(|c| c.as_str()).collect();
        assert_eq!(
            documented, expected,
            "clients.md row set must equal ClientTarget::ALL exactly"
        );

        let project = crate::config::scope::ConfigScope::Project;
        for (name, cells) in &rows {
            let client: ClientTarget = name.parse().unwrap_or_else(|_| panic!("unknown client row '{name}'"));
            let v = client.vendor();
            for (idx, kind) in [ArtifactKind::Skill, ArtifactKind::Rule, ArtifactKind::Agent]
                .into_iter()
                .enumerate()
            {
                let cell =
                    cells[idx].unwrap_or_else(|| panic!("unparsed {kind:?} cell for '{name}' (TODO placeholder?)"));
                let expected = match v.kind_support(kind) {
                    KindSupport::Native => Cell::Yes,
                    KindSupport::Degraded => Cell::Partial,
                    KindSupport::Declined => Cell::No,
                };
                assert_eq!(cell, expected, "{name} {kind:?} cell must track kind_support");
            }
            // MCP column: boolean surface — ✗ ⇔ no config path, ✓/◐ ⇔ some.
            let mcp = cells[3].unwrap_or_else(|| panic!("unparsed MCP cell for '{name}' (TODO placeholder?)"));
            let supported = v.mcp_config_path(Path::new("/w"), project).is_some();
            assert_eq!(mcp != Cell::No, supported, "{name} MCP cell must track mcp_config_path");
        }
    }

    /// Scope `md` to the section starting at the `## …{anchor}` heading
    /// (heading to the next `## `), falling back to the whole document if
    /// the anchor is absent. Shared by every row-presence test below —
    /// each scopes a different doc's client-enumerating section with its
    /// own anchor.
    fn heading_section<'a>(md: &'a str, anchor: &str) -> &'a str {
        let Some(start) = md.find(anchor) else {
            return md;
        };
        let rest = &md[start..];
        match rest[1..].find("\n## ") {
            Some(end) => &rest[..end + 1],
            None => rest,
        }
    }

    /// Whether `word` occurs in `haystack` delimited by non-alphanumeric
    /// boundaries — so a client name like `zed`/`amp` matches its own table
    /// cell or `[zed]` link but not a substring of prose (`materialized`,
    /// `example`). Both args are already lowercased by the callers. Without
    /// this the row-presence guards below could silently go vacuous the day
    /// a section gains such a word.
    fn contains_word(haystack: &str, word: &str) -> bool {
        let boundary = |c: Option<char>| c.is_none_or(|c| !c.is_ascii_alphanumeric());
        haystack.match_indices(word).any(|(i, _)| {
            boundary(haystack[..i].chars().next_back()) && boundary(haystack[i + word.len()..].chars().next())
        })
    }

    /// Emit-matrix row-presence: every `ClientTarget` name appears in the
    /// `docs/src/agents.md` emit-matrix section (catches "added a vendor,
    /// forgot the emit matrix" without over-constraining prose).
    #[test]
    fn agents_emit_matrix_lists_every_client() {
        let md = std::fs::read_to_string(concat!(env!("CARGO_MANIFEST_DIR"), "/docs/src/agents.md"))
            .expect("docs/src/agents.md exists");
        let section = heading_section(&md, "{#emit-matrix}").to_ascii_lowercase();
        for client in ClientTarget::ALL {
            assert!(
                contains_word(&section, client.as_str()),
                "agents.md emit matrix must list every client — missing '{client}'"
            );
        }
    }

    /// Emit-matrix row-presence for `docs/src/mcp-servers.md` — same
    /// invariant as [`agents_emit_matrix_lists_every_client`].
    #[test]
    fn mcp_servers_emit_matrix_lists_every_client() {
        let md = std::fs::read_to_string(concat!(env!("CARGO_MANIFEST_DIR"), "/docs/src/mcp-servers.md"))
            .expect("docs/src/mcp-servers.md exists");
        let section = heading_section(&md, "{#emit-matrix}").to_ascii_lowercase();
        for client in ClientTarget::ALL {
            assert!(
                contains_word(&section, client.as_str()),
                "mcp-servers.md emit matrix must list every client — missing '{client}'"
            );
        }
    }

    /// Row-presence for `docs/src/vendor-metadata.md`'s
    /// `{#discovery-locations}` section (both the project- and
    /// global-scope tables): every `ClientTarget` must appear — skill
    /// discovery is `Native` for all ten, so there is no subset to carve
    /// out (contrast the two tests below, which are Rule/Agent-scoped).
    #[test]
    fn vendor_metadata_discovery_locations_lists_every_client() {
        let md = std::fs::read_to_string(concat!(env!("CARGO_MANIFEST_DIR"), "/docs/src/vendor-metadata.md"))
            .expect("docs/src/vendor-metadata.md exists");
        let section = heading_section(&md, "{#discovery-locations}").to_ascii_lowercase();
        for client in ClientTarget::ALL {
            assert!(
                contains_word(&section, client.as_str()),
                "vendor-metadata.md discovery-locations section must list every client — missing '{client}'"
            );
        }
    }

    /// Row-presence for `docs/src/vendor-metadata.md`'s `{#rule-keys}`
    /// section, scoped to clients that do **not** decline the Rule kind.
    /// The table documents per-client rule-frontmatter field mapping (or,
    /// for Codex, an explicit unsupported note) — the remaining declined
    /// clients (Junie, Gemini, Zed, Amp) have no rule surface to map and
    /// are not required here; their decline is already machine-checked by
    /// [`kind_support_grid_matches_adr_mapping_table`] and the
    /// `clients.md` compat matrix.
    #[test]
    fn vendor_metadata_rule_keys_lists_every_rule_capable_client() {
        use crate::install::vendor::KindSupport;
        let md = std::fs::read_to_string(concat!(env!("CARGO_MANIFEST_DIR"), "/docs/src/vendor-metadata.md"))
            .expect("docs/src/vendor-metadata.md exists");
        let section = heading_section(&md, "{#rule-keys}").to_ascii_lowercase();
        for client in ClientTarget::ALL {
            if client.vendor().kind_support(ArtifactKind::Rule) == KindSupport::Declined {
                continue;
            }
            assert!(
                contains_word(&section, client.as_str()),
                "vendor-metadata.md rule-keys section must list every rule-capable client — missing '{client}'"
            );
        }
    }

    /// Row-presence for `docs/src/agents.md`'s `{#locations}` section,
    /// scoped to clients that do **not** decline the Agent kind — mirrors
    /// [`vendor_metadata_rule_keys_lists_every_rule_capable_client`]: the
    /// four declined clients (Kiro, Junie, Zed, Amp) have no install path
    /// to list, and are already covered by the `{#emit-matrix}` row-
    /// presence test above.
    #[test]
    fn agents_locations_lists_every_agent_capable_client() {
        use crate::install::vendor::KindSupport;
        let md = std::fs::read_to_string(concat!(env!("CARGO_MANIFEST_DIR"), "/docs/src/agents.md"))
            .expect("docs/src/agents.md exists");
        let section = heading_section(&md, "{#locations}").to_ascii_lowercase();
        for client in ClientTarget::ALL {
            if client.vendor().kind_support(ArtifactKind::Agent) == KindSupport::Declined {
                continue;
            }
            assert!(
                contains_word(&section, client.as_str()),
                "agents.md locations section must list every agent-capable client — missing '{client}'"
            );
        }
    }

    /// Row-presence for `docs/src/json-interface.md`'s `options.clients`
    /// `string-set` values list — the literal JSON array of client names
    /// in its `config list` shape description must list every
    /// `ClientTarget`. The paragraph carries no `{#anchor}` heading, so it
    /// is scoped by its own marker text to the next blank line (paragraph
    /// boundary) instead of [`heading_section`]'s `## ` boundary.
    #[test]
    fn json_interface_options_clients_values_lists_every_client() {
        let md = std::fs::read_to_string(concat!(env!("CARGO_MANIFEST_DIR"), "/docs/src/json-interface.md"))
            .expect("docs/src/json-interface.md exists");
        let marker = "`options.clients` is the one `string-set` key";
        let start = md
            .find(marker)
            .expect("json-interface.md must describe options.clients as a string-set key");
        let rest = &md[start..];
        let end = rest.find("\n\n").unwrap_or(rest.len());
        let section = rest[..end].to_ascii_lowercase();
        for client in ClientTarget::ALL {
            assert!(
                contains_word(&section, client.as_str()),
                "json-interface.md options.clients values list must list every client — missing '{client}'"
            );
        }
    }

    #[test]
    fn from_str_and_display_round_trip_lowercase() {
        for (s, t) in [
            ("claude", ClientTarget::Claude),
            ("opencode", ClientTarget::OpenCode),
            ("copilot", ClientTarget::Copilot),
            ("codex", ClientTarget::Codex),
            ("cursor", ClientTarget::Cursor),
            ("kiro", ClientTarget::Kiro),
            ("junie", ClientTarget::Junie),
            ("gemini", ClientTarget::Gemini),
            ("zed", ClientTarget::Zed),
            ("amp", ClientTarget::Amp),
        ] {
            assert_eq!(ClientTarget::from_str(s).unwrap(), t);
            assert_eq!(t.to_string(), s);
        }
        assert!(ClientTarget::from_str("vscode").is_err());
        assert_eq!(ClientTarget::default(), ClientTarget::Claude);
    }

    /// Every client's project-scope layout, read from each vendor's
    /// `skills_root`/`rule_path`/`agent_path` source (`None` marks a kind
    /// the client declines — `kind_support == Declined` — so no on-disk
    /// output is ever written for it; the vendor still implements the
    /// trait method defensively, but that "dead path" is not asserted
    /// here). Iterates [`ClientTarget::ALL`] so a new vendor (#11) fails
    /// this test until its row is added — the array-length assert and the
    /// `kind_support` cross-check both make an incomplete table a build
    /// failure, not a silent gap.
    #[test]
    fn path_for_matches_each_client_layout() {
        use crate::install::vendor::KindSupport;

        let w = Path::new("/w");
        let project = crate::config::scope::ConfigScope::Project;

        let table: [(ClientTarget, &str, Option<&str>, Option<&str>); 10] = [
            (
                ClientTarget::Claude,
                ".claude/skills/x",
                Some(".claude/rules/x.md"),
                Some(".claude/agents/x.md"),
            ),
            (
                ClientTarget::OpenCode,
                ".opencode/skills/x",
                Some(".opencode/rules/x.md"),
                Some(".opencode/agents/x.md"),
            ),
            (
                ClientTarget::Copilot,
                ".github/skills/x",
                Some(".github/instructions/x.instructions.md"),
                Some(".github/agents/x.md"),
            ),
            // Codex: skills land in the cross-vendor `.agents/skills` tree
            // (not `.codex/skills`); agents are TOML under `.codex/agents`;
            // rules are declined.
            (
                ClientTarget::Codex,
                ".agents/skills/x",
                None,
                Some(".codex/agents/x.toml"),
            ),
            (
                ClientTarget::Cursor,
                ".cursor/skills/x",
                Some(".cursor/rules/x.mdc"),
                Some(".cursor/agents/x.md"),
            ),
            // Kiro: rules render as steering docs; agents declined.
            (ClientTarget::Kiro, ".kiro/skills/x", Some(".kiro/steering/x.md"), None),
            // Junie: skills only — rules and agents declined.
            (ClientTarget::Junie, ".junie/skills/x", None, None),
            // Gemini: skills via the shared pool; agents native; rules declined.
            (
                ClientTarget::Gemini,
                ".agents/skills/x",
                None,
                Some(".gemini/agents/x.md"),
            ),
            // Zed / Amp: skills via the shared pool only.
            (ClientTarget::Zed, ".agents/skills/x", None, None),
            (ClientTarget::Amp, ".agents/skills/x", None, None),
        ];
        assert_eq!(
            table.len(),
            ClientTarget::ALL.len(),
            "table must cover every ClientTarget"
        );

        for (client, skill, rule, agent) in table {
            assert_eq!(
                client.path_for(w, project, ArtifactKind::Skill, "x"),
                w.join(skill),
                "{client} skill path"
            );

            assert_eq!(
                rule.is_none(),
                client.vendor().kind_support(ArtifactKind::Rule) == KindSupport::Declined,
                "{client} rule table entry must track kind_support"
            );
            if let Some(rule) = rule {
                assert_eq!(
                    client.path_for(w, project, ArtifactKind::Rule, "x"),
                    w.join(rule),
                    "{client} rule path"
                );
            }

            assert_eq!(
                agent.is_none(),
                client.vendor().kind_support(ArtifactKind::Agent) == KindSupport::Declined,
                "{client} agent table entry must track kind_support"
            );
            if let Some(agent) = agent {
                assert_eq!(
                    client.path_for(w, project, ArtifactKind::Agent, "x"),
                    w.join(agent),
                    "{client} agent path"
                );
            }
        }
    }

    #[test]
    fn path_for_global_scope_uses_vendor_native_roots() {
        let w = Path::new("/grim-home");
        let g = crate::config::scope::ConfigScope::Global;
        // Native user-level discovery paths (resolvable in any env that
        // has $HOME — the fallback keeps the workspace layout otherwise).
        if let Some(home) = crate::install::vendor::home_dir() {
            assert_eq!(
                ClientTarget::Claude.path_for(w, g, ArtifactKind::Skill, "x"),
                home.join(".claude/skills/x")
            );
            assert_eq!(
                ClientTarget::Claude.path_for(w, g, ArtifactKind::Rule, "r"),
                home.join(".claude/rules/r.md")
            );
            assert_eq!(
                ClientTarget::Copilot.path_for(w, g, ArtifactKind::Skill, "x"),
                home.join(".copilot/skills/x")
            );
            // Codex skills follow the cross-vendor `$HOME/.agents/skills`
            // standard — NOT `$CODEX_HOME` (proven by the agent path below).
            assert_eq!(
                ClientTarget::Codex.path_for(w, g, ArtifactKind::Skill, "x"),
                home.join(".agents/skills/x")
            );
            // Codex agents live under `$CODEX_HOME|~/.codex` + `agents/`; the
            // env-override order is unit-tested in vendor_codex, so only assert
            // the `~/.codex` default when CODEX_HOME is unset.
            if crate::install::vendor::env_dir("CODEX_HOME").is_none() {
                assert_eq!(
                    ClientTarget::Codex.path_for(w, g, ArtifactKind::Agent, "rev"),
                    home.join(".codex/agents/rev.toml")
                );
            }
        }
        if let Some(cfg) = crate::install::vendor::xdg_config_dir() {
            assert_eq!(
                ClientTarget::OpenCode.path_for(w, g, ArtifactKind::Skill, "x"),
                cfg.join("opencode/skills/x")
            );
        }
        // OpenCode rules stay in the workspace layout (loaded via the
        // absolute instructions glob); Copilot rules route to the native
        // `$COPILOT_HOME|~/.copilot/instructions/` dir.
        assert_eq!(
            ClientTarget::OpenCode.path_for(w, g, ArtifactKind::Rule, "r"),
            PathBuf::from("/grim-home/.opencode/rules/r.md")
        );
        if let Some(home) = crate::install::vendor::home_dir()
            && crate::install::vendor::env_dir("COPILOT_HOME").is_none()
        {
            assert_eq!(
                ClientTarget::Copilot.path_for(w, g, ArtifactKind::Rule, "r"),
                home.join(".copilot/instructions/r.instructions.md")
            );
        }
    }

    #[test]
    fn materialize_rule_claude_is_verbatim() {
        let tmp = tempfile::tempdir().unwrap();
        let src = tmp.path().join("rust-style.md");
        std::fs::write(&src, "---\npaths: [\"a\"]\n---\n# R\n").unwrap();
        let dest = tmp.path().join(".claude/rules/rust-style.md");
        let files = ClientTarget::Claude
            .materialize(MaterializeRequest {
                kind: ArtifactKind::Rule,
                name: "rust-style",
                artifact_root: &src,
                dest: &dest,
                scope: ConfigScope::Project,
                pinned: "p",
                support_dir: None,
            })
            .unwrap();
        assert_eq!(files.len(), 1);
        assert!(!files[0].generated);
        assert_eq!(
            std::fs::read_to_string(&dest).unwrap(),
            "---\npaths: [\"a\"]\n---\n# R\n"
        );
    }

    #[test]
    fn materialize_rule_copilot_is_generated_transform() {
        let tmp = tempfile::tempdir().unwrap();
        let src = tmp.path().join("rust-style.md");
        std::fs::write(&src, "---\npaths: [\"a\"]\n---\n# R\nbody\n").unwrap();
        let dest = tmp.path().join(".github/instructions/rust-style.instructions.md");
        let files = ClientTarget::Copilot
            .materialize(MaterializeRequest {
                kind: ArtifactKind::Rule,
                name: "rust-style",
                artifact_root: &src,
                dest: &dest,
                scope: ConfigScope::Project,
                pinned: "pin",
                support_dir: None,
            })
            .unwrap();
        assert!(files[0].generated);
        let body = std::fs::read_to_string(&dest).unwrap();
        assert!(body.starts_with("---\napplyTo: \"a\"\n---\n<!-- generated by grim from pin;"));
        assert!(!body.contains("paths:"));
    }

    #[test]
    fn materialize_rule_opencode_is_generated_body_only() {
        let tmp = tempfile::tempdir().unwrap();
        let src = tmp.path().join("rust-style.md");
        std::fs::write(&src, "---\npaths: [\"a\"]\n---\n# R\nbody\n").unwrap();
        let dest = tmp.path().join(".opencode/rules/rust-style.md");
        let files = ClientTarget::OpenCode
            .materialize(MaterializeRequest {
                kind: ArtifactKind::Rule,
                name: "rust-style",
                artifact_root: &src,
                dest: &dest,
                scope: ConfigScope::Project,
                pinned: "pin",
                support_dir: None,
            })
            .unwrap();
        assert!(files[0].generated);
        let body = std::fs::read_to_string(&dest).unwrap();
        assert!(body.starts_with("<!-- generated by grim from pin;"));
        assert!(!body.contains("paths:"), "frontmatter stripped for OpenCode");
    }

    #[test]
    fn materialize_rule_claude_with_vendor_metadata_is_generated_cleaned() {
        // Rule symmetry with skills: a rule carrying tool-namespaced
        // metadata is re-rendered for Claude too — foreign vendor keys do
        // not leak into `.claude/rules/`, the file is generated.
        let tmp = tempfile::tempdir().unwrap();
        let src = tmp.path().join("rust-style.md");
        std::fs::write(
            &src,
            "---\npaths: [\"**/*.rs\"]\nkeywords: rust\nmetadata:\n  copilot.exclude-agent: code-review\n---\n# R\nbody\n",
        )
        .unwrap();
        let dest = tmp.path().join(".claude/rules/rust-style.md");
        let files = ClientTarget::Claude
            .materialize(MaterializeRequest {
                kind: ArtifactKind::Rule,
                name: "rust-style",
                artifact_root: &src,
                dest: &dest,
                scope: ConfigScope::Project,
                pinned: "p",
                support_dir: None,
            })
            .unwrap();
        assert!(files[0].generated, "cleaned render is a generated file");
        let body = std::fs::read_to_string(&dest).unwrap();
        assert!(!body.contains("copilot.exclude-agent"), "foreign vendor key dropped");
        assert!(body.contains("**/*.rs"), "native paths scoping kept");
        assert!(body.contains("keywords: rust"), "plain catalog key kept");
        assert!(body.ends_with("# R\nbody\n"));
    }

    #[test]
    fn materialize_skill_copies_tree_verbatim_all_clients() {
        let tmp = tempfile::tempdir().unwrap();
        let root = tmp.path().join("code-review");
        std::fs::create_dir_all(root.join("scripts")).unwrap();
        std::fs::write(root.join("SKILL.md"), "---\nname: code-review\ndescription: d\n---\n").unwrap();
        std::fs::write(root.join("scripts/run.sh"), "echo hi\n").unwrap();

        // Every vendor's `skill_index` returns `None` (verbatim install) for
        // a doc carrying no vendor-namespaced metadata — the six vendor-aware
        // vendors via `render::render_skill_doc`, the four shared-pool vendors
        // via `render::render_universal_skill_doc` — so this fixture's fast
        // path is vendor-independent and must hold for all 10.
        for client in ClientTarget::ALL {
            let dest = tmp.path().join(format!("out-{client}/code-review"));
            let files = client
                .materialize(MaterializeRequest {
                    kind: ArtifactKind::Skill,
                    name: "code-review",
                    artifact_root: &root,
                    dest: &dest,
                    scope: ConfigScope::Project,
                    pinned: "p",
                    support_dir: None,
                })
                .unwrap();
            assert_eq!(files.len(), 2);
            assert!(files.iter().all(|f| !f.generated));
            assert_eq!(
                std::fs::read_to_string(dest.join("SKILL.md")).unwrap(),
                "---\nname: code-review\ndescription: d\n---\n"
            );
            assert_eq!(
                std::fs::read_to_string(dest.join("scripts/run.sh")).unwrap(),
                "echo hi\n"
            );
        }
    }

    #[test]
    fn materialize_rule_with_support_dir_claude_verbatim() {
        // The index lands verbatim (paths: is native) and the support tree
        // is copied beside it at `<dest_parent>/<name>/`.
        let tmp = tempfile::tempdir().unwrap();
        let src = tmp.path().join("my-rule.md");
        std::fs::write(&src, "---\npaths: [\"a\"]\n---\n# index\n").unwrap();
        let support = tmp.path().join("my-rule");
        std::fs::create_dir_all(support.join("nested")).unwrap();
        std::fs::write(support.join("examples.md"), "# ex\n").unwrap();
        std::fs::write(support.join("nested/schema.json"), "{}\n").unwrap();

        let dest = tmp.path().join(".claude/rules/my-rule.md");
        let files = ClientTarget::Claude
            .materialize(MaterializeRequest {
                kind: ArtifactKind::Rule,
                name: "my-rule",
                artifact_root: &src,
                dest: &dest,
                scope: ConfigScope::Project,
                pinned: "p",
                support_dir: Some(support.as_path()),
            })
            .unwrap();

        assert!(files.iter().all(|f| !f.generated), "verbatim copies are not generated");
        let support_dest = dest.parent().unwrap().join("my-rule");
        assert_eq!(
            std::fs::read_to_string(&dest).unwrap(),
            "---\npaths: [\"a\"]\n---\n# index\n"
        );
        assert_eq!(
            std::fs::read_to_string(support_dest.join("examples.md")).unwrap(),
            "# ex\n"
        );
        assert_eq!(
            std::fs::read_to_string(support_dest.join("nested/schema.json")).unwrap(),
            "{}\n"
        );
    }

    #[test]
    fn materialize_rule_with_support_dir_opencode_transforms_index_copies_support() {
        // OpenCode transforms the index (body + provenance); the support
        // dir is copied verbatim beside it so relative links resolve.
        let tmp = tempfile::tempdir().unwrap();
        let src = tmp.path().join("my-rule.md");
        std::fs::write(&src, "---\npaths: [\"a\"]\n---\n# index\n").unwrap();
        let support = tmp.path().join("my-rule");
        std::fs::create_dir_all(&support).unwrap();
        std::fs::write(support.join("examples.md"), "# ex\n").unwrap();

        let dest = tmp.path().join(".opencode/rules/my-rule.md");
        let files = ClientTarget::OpenCode
            .materialize(MaterializeRequest {
                kind: ArtifactKind::Rule,
                name: "my-rule",
                artifact_root: &src,
                dest: &dest,
                scope: ConfigScope::Project,
                pinned: "p",
                support_dir: Some(support.as_path()),
            })
            .unwrap();

        assert_eq!(files.iter().filter(|f| f.generated).count(), 1);
        let index = std::fs::read_to_string(&dest).unwrap();
        assert!(index.starts_with("<!-- generated by grim from p;"));
        assert!(!index.contains("paths:"));
        assert_eq!(
            std::fs::read_to_string(dest.parent().unwrap().join("my-rule/examples.md")).unwrap(),
            "# ex\n"
        );
    }

    #[test]
    fn materialize_skill_with_namespaced_metadata_renders_per_client() {
        let tmp = tempfile::tempdir().unwrap();
        let root = tmp.path().join("next");
        std::fs::create_dir_all(root.join("scripts")).unwrap();
        let canonical = "---\nname: next\ndescription: d\nmetadata:\n  keywords: a,b\n  claude.user-invocable: \"false\"\n---\n# body\n";
        std::fs::write(root.join("SKILL.md"), canonical).unwrap();
        std::fs::write(root.join("scripts/run.sh"), "echo hi\n").unwrap();

        for client in [
            ClientTarget::Claude,
            ClientTarget::OpenCode,
            ClientTarget::Copilot,
            ClientTarget::Codex,
        ] {
            let dest = tmp.path().join(format!("out-{client}/next"));
            let files = client
                .materialize(MaterializeRequest {
                    kind: ArtifactKind::Skill,
                    name: "next",
                    artifact_root: &root,
                    dest: &dest,
                    scope: ConfigScope::Project,
                    pinned: "p",
                    support_dir: None,
                })
                .unwrap();
            // The rendered index is generated; the sibling stays verbatim.
            let index = dest.join("SKILL.md");
            assert!(
                files.iter().any(|f| f.path == index && f.generated),
                "{client}: SKILL.md must be generated"
            );
            assert!(
                files
                    .iter()
                    .any(|f| f.path == dest.join("scripts/run.sh") && !f.generated),
                "{client}: siblings stay verbatim"
            );
            let doc = std::fs::read_to_string(&index).unwrap();
            assert!(
                !doc.contains("claude.user-invocable"),
                "{client}: namespaced key lifted/dropped"
            );
            assert!(doc.contains("keywords: a,b"), "{client}: plain metadata kept");
            if client == ClientTarget::Claude {
                assert!(doc.contains("user-invocable: false"), "native typed field for Claude");
            } else {
                assert!(!doc.contains("user-invocable"), "{client}: clean universal SKILL.md");
            }
        }
    }

    #[test]
    fn materialize_skill_without_namespaced_metadata_is_byte_identical() {
        let tmp = tempfile::tempdir().unwrap();
        let root = tmp.path().join("plain");
        std::fs::create_dir_all(&root).unwrap();
        let canonical = "---\nname: plain\ndescription: d\nmetadata:\n  keywords: a,b\n---\n# body\n";
        std::fs::write(root.join("SKILL.md"), canonical).unwrap();

        for client in [
            ClientTarget::Claude,
            ClientTarget::OpenCode,
            ClientTarget::Copilot,
            ClientTarget::Codex,
        ] {
            let dest = tmp.path().join(format!("out-{client}/plain"));
            let files = client
                .materialize(MaterializeRequest {
                    kind: ArtifactKind::Skill,
                    name: "plain",
                    artifact_root: &root,
                    dest: &dest,
                    scope: ConfigScope::Project,
                    pinned: "p",
                    support_dir: None,
                })
                .unwrap();
            assert!(files.iter().all(|f| !f.generated), "{client}: verbatim fast path");
            assert_eq!(
                std::fs::read_to_string(dest.join("SKILL.md")).unwrap(),
                canonical,
                "{client}: byte-identical install"
            );
        }
    }

    #[test]
    fn materialize_skill_rebound_binding_rewrites_frontmatter_name() {
        // Regression: a `--name` rebinding (binding ≠ frontmatter name)
        // must keep the Agent Skills directory-equality rule true at the
        // destination — the installed SKILL.md carries the binding as its
        // `name`, is marked generated, and every other key plus the body
        // survives. Siblings stay verbatim.
        let tmp = tempfile::tempdir().unwrap();
        let root = tmp.path().join("foo");
        std::fs::create_dir_all(root.join("scripts")).unwrap();
        std::fs::write(
            root.join("SKILL.md"),
            "---\nname: foo\ndescription: d\nmetadata:\n  keywords: a,b\n---\n# body\n",
        )
        .unwrap();
        std::fs::write(root.join("scripts/run.sh"), "echo hi\n").unwrap();

        for client in [ClientTarget::Claude, ClientTarget::OpenCode, ClientTarget::Copilot] {
            let dest = tmp.path().join(format!("out-{client}/bar"));
            let files = client
                .materialize(MaterializeRequest {
                    kind: ArtifactKind::Skill,
                    name: "bar",
                    artifact_root: &root,
                    dest: &dest,
                    scope: ConfigScope::Project,
                    pinned: "p",
                    support_dir: None,
                })
                .unwrap();
            let index = dest.join("SKILL.md");
            assert!(
                files.iter().any(|f| f.path == index && f.generated),
                "{client}: rebound SKILL.md must be generated"
            );
            let doc = std::fs::read_to_string(&index).unwrap();
            assert!(doc.contains("name: bar"), "{client}: name rewritten to binding: {doc}");
            assert!(!doc.contains("name: foo"), "{client}: stale name gone: {doc}");
            assert!(doc.contains("keywords: a,b"), "{client}: plain metadata kept: {doc}");
            assert!(doc.ends_with("# body\n"), "{client}: body preserved: {doc}");
            assert_eq!(
                std::fs::read_to_string(dest.join("scripts/run.sh")).unwrap(),
                "echo hi\n",
                "{client}: siblings stay verbatim"
            );
        }
    }

    #[test]
    fn materialize_rule_with_support_dir_copilot_transforms_index_copies_support() {
        // Copilot transforms only the index; the support dir is copied
        // verbatim beside it at `.github/instructions/<name>/`.
        let tmp = tempfile::tempdir().unwrap();
        let src = tmp.path().join("my-rule.md");
        std::fs::write(&src, "---\npaths: [\"a\"]\n---\n# index\nbody\n").unwrap();
        let support = tmp.path().join("my-rule");
        std::fs::create_dir_all(&support).unwrap();
        std::fs::write(support.join("examples.md"), "# ex\n").unwrap();

        let dest = tmp.path().join(".github/instructions/my-rule.instructions.md");
        let files = ClientTarget::Copilot
            .materialize(MaterializeRequest {
                kind: ArtifactKind::Rule,
                name: "my-rule",
                artifact_root: &src,
                dest: &dest,
                scope: ConfigScope::Project,
                pinned: "pin",
                support_dir: Some(support.as_path()),
            })
            .unwrap();

        // The index is the single generated file; support files are verbatim.
        assert_eq!(files.iter().filter(|f| f.generated).count(), 1);
        let index = std::fs::read_to_string(&dest).unwrap();
        assert!(index.starts_with("---\napplyTo: \"a\"\n---\n<!-- generated by grim from pin;"));
        assert!(!index.contains("paths:"), "canonical frontmatter mapped, not copied");
        let support_dest = dest.parent().unwrap().join("my-rule");
        assert_eq!(
            std::fs::read_to_string(support_dest.join("examples.md")).unwrap(),
            "# ex\n"
        );
    }
}
