// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 The Grimoire Authors

//! The client-transform seam: turn a materialized canonical artifact tree
//! into the on-disk layout one client expects.
//!
//! **Skills**: every client copies the tree verbatim, except `SKILL.md`
//! when it carries tool-namespaced metadata (`claude.<field>: "…"`): then
//! the index is projected per client via [`super::render`] — Claude gets
//! the native typed fields lifted to the top level; OpenCode/Copilot get
//! a clean universal frontmatter with the tool keys removed.
//!
//! **Rules**: Claude copies the index verbatim (`paths:` is native).
//! OpenCode rewrites it to provenance + body — OpenCode has no per-file
//! path scoping; the file is loaded via the managed `instructions` entry
//! in `opencode.json` (see `opencode_config`). Copilot rewrites it to a
//! `<name>.instructions.md` whose frontmatter maps `paths` → `applyTo`
//! (comma-joined) and `copilot.exclude-agent` → `excludeAgent`.
//!
//! Every transform is deterministic — regenerating the same artifact at
//! the same pinned identifier yields byte-identical output, so a user
//! edit to a generated file is detected as drift exactly like a canonical
//! file (the installer hashes the *expected* generated bytes, not the
//! input).

use std::path::{Path, PathBuf};

use crate::config::scope::ConfigScope;
use crate::oci::ArtifactKind;
use crate::oci::hook::{CanonicalEvent, HookEntry, HookHandler, HookTier};
use crate::skill::{AgentFrontmatter, RuleFrontmatter};
use crate::store::atomic_write::atomic_write;

use super::install_error::{InstallError, InstallErrorKind};

use super::hook_dispatch::RootToken;
use super::vendor::{KindSupport, Vendor};
use super::vendor_agents::AgentsVendor;
use super::vendor_amp::AmpVendor;
use super::vendor_antigravity::AntigravityVendor;
use super::vendor_claude::ClaudeVendor;
use super::vendor_cline::ClineVendor;
use super::vendor_codex::CodexVendor;
use super::vendor_copilot::CopilotVendor;
use super::vendor_cursor::CursorVendor;
use super::vendor_droid::DroidVendor;
use super::vendor_gemini::GeminiVendor;
use super::vendor_goose::GooseVendor;
use super::vendor_junie::JunieVendor;
use super::vendor_kilo::KiloVendor;
use super::vendor_kiro::KiroVendor;
use super::vendor_openclaw::OpenClawVendor;
use super::vendor_opencode::OpenCodeVendor;
use super::vendor_warp::WarpVendor;
use super::vendor_zed::ZedVendor;

/// A supported client target.
///
/// Closed internal enum (the binary is the only consumer); `Default` is
/// [`ClientTarget::Claude`].
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub enum ClientTarget {
    /// Claude Code — `.claude/{skills,rules}`.
    #[default]
    Claude,
    /// OpenCode — `.opencode/{skills,rules}`.
    OpenCode,
    /// GitHub Copilot — `.github/{skills,instructions}` (rules transformed).
    Copilot,
    /// OpenAI Codex — `.agents/skills` + `.codex/agents/<name>.toml`
    /// (skills + agents only; rules unsupported).
    Codex,
    /// Cursor — `.cursor/{skills,rules,agents,mcp.json}` (all four kinds
    /// native; rules render to `.mdc`).
    Cursor,
    /// Kiro (AWS) — `.kiro/{skills,steering,settings/mcp.json}` (skills,
    /// rules, MCP; agents declined — CLI/IDE schema collision).
    Kiro,
    /// JetBrains Junie — `.junie/{skills,rules,mcp/mcp.json}` (skills + MCP
    /// native; rules **degraded and project-only** — `.junie/rules/` is
    /// ownable but concatenated wholesale, so `paths` is dropped, and no
    /// global `~/.junie/rules/` exists; agents declined — EAP-only).
    Junie,
    /// Gemini CLI — shared `.agents/skills` + `.gemini/{agents,settings.json}`
    /// (skills, agents, MCP; rules declined — GEMINI.md hierarchy only).
    Gemini,
    /// Zed — shared `.agents/skills` + `.zed/settings.json` (skills + MCP;
    /// rules and agents declined — no scoping / ACP-only agents).
    Zed,
    /// Amp — shared `.agents/skills` + `.amp/settings.json` (skills + MCP;
    /// rules and agents declined — AGENTS.md only / runtime subagents).
    Amp,
    /// The vendor-neutral generic client — shared `.agents/skills` only
    /// (rules, agents, and MCP declined: no vendor-neutral surface exists).
    /// Not a product. Never detected, only selected: today solely by explicit
    /// request (`--client agents`, `[options].clients`). See
    /// [`AgentsVendor::detect`](super::vendor_agents::AgentsVendor).
    Agents,
    /// Google Antigravity 2.0 — shared `.agents/skills` at project scope, its
    /// own `~/.gemini/config` root globally, plus `.agents/agents` and
    /// `.agents/mcp_config.json` (skills, agents, MCP; rules declined — the
    /// global surface is a shared monolithic `GEMINI.md`). Targets the 2.0
    /// desktop product; the Antigravity CLI and IDE variants read different
    /// global directories and are not served by this name.
    Antigravity,
    /// Cline — `.cline/skills` (skills only; rules, agents, and MCP declined).
    /// A documented non-adopter of the shared `.agents/skills` pool.
    Cline,
    /// Droid (Factory) — `.factory/skills` (skills only). The client is
    /// `droid`; its directory is `.factory`. That mismatch is deliberate.
    Droid,
    /// Goose (Block) — shared `.agents/skills` at both scopes (skills only).
    /// The one client in its batch that renders to the pool: its own
    /// `.goose/skills` is labelled back-compat upstream.
    Goose,
    /// Warp — `.warp/skills` (skills only). Renders natively but is
    /// pool-*capable*, so it can be opted into `.agents/skills`.
    Warp,
    /// OpenClaw — `~/.openclaw/skills`, **global scope only**: its "project"
    /// path is a fixed daemon home that does not track the repository.
    OpenClaw,
    /// Kilo — `.kilo/skills` (skills only). Never writes the deprecated
    /// `.kilocode`; a partial pool member, so off the shared-pool roster.
    Kilo,
}

impl std::str::FromStr for ClientTarget {
    type Err = InstallError;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s {
            "claude" => Ok(Self::Claude),
            "opencode" => Ok(Self::OpenCode),
            "copilot" => Ok(Self::Copilot),
            "codex" => Ok(Self::Codex),
            "cursor" => Ok(Self::Cursor),
            "kiro" => Ok(Self::Kiro),
            "junie" => Ok(Self::Junie),
            "gemini" => Ok(Self::Gemini),
            "zed" => Ok(Self::Zed),
            "amp" => Ok(Self::Amp),
            "agents" => Ok(Self::Agents),
            "antigravity" => Ok(Self::Antigravity),
            "cline" => Ok(Self::Cline),
            "droid" => Ok(Self::Droid),
            "goose" => Ok(Self::Goose),
            "warp" => Ok(Self::Warp),
            "openclaw" => Ok(Self::OpenClaw),
            "kilo" => Ok(Self::Kilo),
            other => Err(InstallError::without_reference(InstallErrorKind::UnsupportedClient(
                other.to_string(),
            ))),
        }
    }
}

impl std::fmt::Display for ClientTarget {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(self.as_str())
    }
}

impl ClientTarget {
    /// The canonical lowercase name for this client (`claude` / `opencode` /
    /// `copilot` / `codex`). Zero-alloc form of [`Display`]; round-trips
    /// through [`std::str::FromStr`]. Used to compare against the stored
    /// [`super::install_state::ClientOutput::client`] string without an
    /// intermediate allocation.
    pub const fn as_str(&self) -> &'static str {
        match self {
            Self::Claude => "claude",
            Self::OpenCode => "opencode",
            Self::Copilot => "copilot",
            Self::Codex => "codex",
            Self::Cursor => "cursor",
            Self::Kiro => "kiro",
            Self::Junie => "junie",
            Self::Gemini => "gemini",
            Self::Zed => "zed",
            Self::Amp => "amp",
            Self::Agents => "agents",
            Self::Antigravity => "antigravity",
            Self::Cline => "cline",
            Self::Droid => "droid",
            Self::Goose => "goose",
            Self::Warp => "warp",
            Self::OpenClaw => "openclaw",
            Self::Kilo => "kilo",
        }
    }

    /// The stable lowercase identifier for each variant, in declaration
    /// order — the single list `command::config_keys` presents as the
    /// `options.clients` config key's allowed values (mirrors
    /// [`crate::config::declaration::DefaultView::VALUE_NAMES`]).
    pub const VALUE_NAMES: &'static [&'static str] = &[
        Self::Claude.as_str(),
        Self::OpenCode.as_str(),
        Self::Copilot.as_str(),
        Self::Codex.as_str(),
        Self::Cursor.as_str(),
        Self::Kiro.as_str(),
        Self::Junie.as_str(),
        Self::Gemini.as_str(),
        Self::Zed.as_str(),
        Self::Amp.as_str(),
        Self::Agents.as_str(),
        Self::Antigravity.as_str(),
        Self::Cline.as_str(),
        Self::Droid.as_str(),
        Self::Goose.as_str(),
        Self::Warp.as_str(),
        Self::OpenClaw.as_str(),
        Self::Kilo.as_str(),
    ];
}

/// One file produced for an client target.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct MaterializedFile {
    /// The absolute on-disk path written.
    pub path: PathBuf,
    /// Whether the file is a generated transform (vs. a canonical copy).
    /// Generated files are integrity-hashed against their *expected*
    /// bytes so a user edit is still detected as drift.
    pub generated: bool,
}

/// The inputs to [`ClientTarget::materialize`]: what to materialize, from
/// where, and to where. Bundled into one struct so the entry point stays a
/// two-argument call and each field is named at the call site.
#[derive(Debug, Clone, Copy)]
pub struct MaterializeRequest<'a> {
    /// The artifact kind (skill / rule / agent).
    pub kind: ArtifactKind,
    /// The binding name (may differ from the canonical frontmatter name).
    pub name: &'a str,
    /// The extracted canonical content root: the skill directory
    /// (`<name>/…`) or the rule / agent index file (`<name>.md`).
    pub artifact_root: &'a Path,
    /// The final on-disk destination from [`ClientTarget::path_for`].
    pub dest: &'a Path,
    /// The install scope.
    pub scope: ConfigScope,
    /// The pinned identifier stamped into generated-file provenance.
    pub pinned: &'a str,
    /// The optional sibling support directory of a multi-file rule.
    pub support_dir: Option<&'a Path>,
}

impl ClientTarget {
    /// Every supported client, in canonical order.
    pub const ALL: [ClientTarget; 18] = [
        Self::Claude,
        Self::OpenCode,
        Self::Copilot,
        Self::Codex,
        Self::Cursor,
        Self::Kiro,
        Self::Junie,
        Self::Gemini,
        Self::Zed,
        Self::Amp,
        Self::Agents,
        Self::Antigravity,
        Self::Cline,
        Self::Droid,
        Self::Goose,
        Self::Warp,
        Self::OpenClaw,
        Self::Kilo,
    ];

    /// The per-vendor materialization strategy behind this identity.
    pub fn vendor(self) -> &'static dyn Vendor {
        match self {
            Self::Claude => &ClaudeVendor,
            Self::OpenCode => &OpenCodeVendor,
            Self::Copilot => &CopilotVendor,
            Self::Codex => &CodexVendor,
            Self::Cursor => &CursorVendor,
            Self::Kiro => &KiroVendor,
            Self::Junie => &JunieVendor,
            Self::Gemini => &GeminiVendor,
            Self::Zed => &ZedVendor,
            Self::Amp => &AmpVendor,
            Self::Agents => &AgentsVendor,
            Self::Antigravity => &AntigravityVendor,
            Self::Cline => &ClineVendor,
            Self::Droid => &DroidVendor,
            Self::Goose => &GooseVendor,
            Self::Warp => &WarpVendor,
            Self::OpenClaw => &OpenClawVendor,
            Self::Kilo => &KiloVendor,
        }
    }

    /// The absolute install path for the named artifact of `kind` under
    /// `workspace` at `scope`. A skill installs as a directory; a rule as
    /// a single file. Project scope lands under `<workspace>/<root_dir>`;
    /// global scope lands in the vendor's native user-level discovery
    /// location (see [`Vendor::skills_root`] / [`Vendor::rule_path`]).
    pub fn path_for(
        self,
        workspace: &Path,
        scope: crate::config::scope::ConfigScope,
        kind: ArtifactKind,
        name: &str,
    ) -> PathBuf {
        match kind {
            // A hook payload is **client-independent** (S-003) *and*
            // machine-local at both scopes (SEC-1, invariant I1) — so its
            // location is a function of `$GRIM_HOME`, which this seam never
            // receives. `workspace` happens to BE `$GRIM_HOME` at global scope,
            // which is how the project arm came to be written against the
            // workspace in the first place; the fix is to route both scopes
            // through the one function that takes `$GRIM_HOME` explicitly.
            //
            // Provably unreachable: `InstallTarget::path_for` — the only
            // production caller of this function — intercepts `Hook` and
            // delegates to `hook_dispatch::payload_dir` before it ever gets
            // here (pinned by `install_target_path_for_never_delegates_a_hook`
            // in `target.rs`). Same shape as the `Bundle` arm below rather than
            // a plausible-looking fallback, because a fallback returning a
            // workspace path is exactly the defect this arm used to be.
            ArtifactKind::Hook => unreachable!(
                "hook payloads are machine-local (I1); route through InstallTarget::path_for, \
                 which delegates to install::hook_dispatch::payload_dir"
            ),
            ArtifactKind::Skill => self.vendor().skills_root(workspace, scope).join(name),
            ArtifactKind::Rule => self.vendor().rule_path(workspace, scope, name),
            ArtifactKind::Agent => self.vendor().agent_path(workspace, scope, name),
            // An MCP descriptor registers into the vendor's MCP config file
            // (no file of its own); the config path is the reportable
            // target. The workspace-conventional `.mcp.json` stands in when
            // the vendor has no surface for this scope (report-only — the
            // install itself skips such a vendor).
            ArtifactKind::Mcp => self
                .vendor()
                .mcp_config_path(workspace, scope)
                .unwrap_or_else(|| workspace.join(".mcp.json")),
            // Bundles never materialize; they expand into members.
            ArtifactKind::Bundle => unreachable!("bundles are never materialized; they expand into members"),
        }
    }

    /// Materialize the canonical artifact tree at `artifact_root` into the
    /// client layout at `dest`.
    ///
    /// `artifact_root` is the extracted canonical content: the skill
    /// directory (`<name>/…`) or the rule index file (`<name>.md`). `dest`
    /// is the final path from [`Self::path_for`]. For a skill, the tree is
    /// copied verbatim. For a rule, Claude/OpenCode copy the index verbatim;
    /// Copilot transforms it (strip `paths:`, prepend provenance header).
    ///
    /// `support_dir` is the optional sibling support directory of a
    /// multi-file rule (`<root>/<name>/`). When present it is copied
    /// verbatim — for every client, including Copilot — beside the index at
    /// `<dest_parent>/<name>/`, so the index's relative links resolve. Only
    /// the index is ever transformed.
    ///
    /// A **hook** payload copies verbatim like a skill but with no index render
    /// and no per-client branch at all — see [`Self::materialize_hook`].
    ///
    /// # Errors
    ///
    /// [`InstallErrorKind::TargetIo`] for a filesystem failure;
    /// [`InstallErrorKind::MaterializeFailed`] for an unreadable rule.
    pub fn materialize(self, req: MaterializeRequest<'_>) -> Result<Vec<MaterializedFile>, InstallError> {
        let MaterializeRequest {
            kind,
            name,
            artifact_root,
            dest,
            scope,
            pinned,
            support_dir,
        } = req;
        match kind {
            ArtifactKind::Hook => Self::materialize_hook(artifact_root, dest),
            ArtifactKind::Skill => self.materialize_skill(name, artifact_root, dest),
            ArtifactKind::Rule => self.materialize_rule(name, artifact_root, dest, scope, pinned, support_dir),
            ArtifactKind::Agent => self.materialize_agent(artifact_root, dest, pinned),
            // Bundles never materialize; they expand into members.
            ArtifactKind::Bundle => unreachable!("bundles are never materialized; they expand into members"),
            // MCP descriptors register into client configs; the installer
            // diverges before the materialization path.
            ArtifactKind::Mcp => unreachable!("mcp descriptors register into client configs, never materialize"),
        }
    }

    /// Copy a skill tree into `dest`. Every file copies verbatim except
    /// `SKILL.md` when it carries tool-namespaced metadata: that index is
    /// rendered per client (and marked `generated`, so the integrity hash
    /// anchors on the *expected rendered* bytes). A `--name` rebinding
    /// (binding `name` ≠ frontmatter name) rewrites the frontmatter
    /// `name` to the binding first — the Agent Skills directory-equality
    /// rule must hold at the destination — and that index is generated
    /// even for a vendor that would otherwise copy verbatim. A plain
    /// skill under its own name — or a `SKILL.md` that does not parse —
    /// installs byte-identical to the canonical tree, preserving the
    /// historical verbatim contract.
    fn materialize_skill(
        self,
        name: &str,
        artifact_root: &Path,
        dest: &Path,
    ) -> Result<Vec<MaterializedFile>, InstallError> {
        let mut out = Vec::new();
        copy_tree(artifact_root, dest, &mut out)?;

        let index_src = artifact_root.join("SKILL.md");
        if index_src.is_file() {
            let doc_bytes = std::fs::read(&index_src).map_err(|e| target_io(&index_src, e))?;
            let doc = String::from_utf8_lossy(&doc_bytes);
            // Rebind BEFORE the vendor render so every vendor projects
            // from the corrected document.
            let rebound = super::render::rebind_skill_name(&doc, name);
            let effective = rebound.as_deref().unwrap_or(&doc);
            let rendered = self
                .vendor()
                .skill_index(effective)
                .map_err(|e| materialize_failed(e.to_string()))?;
            let generated_doc = match rendered {
                Some(rendered) => {
                    for warning in &rendered.warnings {
                        tracing::warn!("{warning}");
                    }
                    Some(rendered.document)
                }
                // No vendor transform — but a rebound index is still a
                // generated file, never the canonical bytes.
                None => rebound,
            };
            if let Some(text) = generated_doc {
                let index_dest = dest.join("SKILL.md");
                atomic_write(&index_dest, text.as_bytes()).map_err(|e| target_io(&index_dest, e))?;
                for file in &mut out {
                    if file.path == index_dest {
                        file.generated = true;
                    }
                }
            }
        }

        out.sort_by(|a, b| a.path.cmp(&b.path));
        Ok(out)
    }

    /// Materialize a rule: the index goes through the vendor's
    /// [`Vendor::rule_index`] transform (`None` ⇒ verbatim copy); an
    /// optional support directory is copied verbatim beside the index for
    /// every client.
    fn materialize_rule(
        self,
        name: &str,
        artifact_root: &Path,
        dest: &Path,
        scope: ConfigScope,
        pinned: &str,
        support_dir: Option<&Path>,
    ) -> Result<Vec<MaterializedFile>, InstallError> {
        let bytes = std::fs::read(artifact_root).map_err(|e| target_io(artifact_root, e))?;
        if let Some(parent) = dest.parent() {
            std::fs::create_dir_all(parent).map_err(|e| target_io(parent, e))?;
        }

        let doc = String::from_utf8_lossy(&bytes);
        let parsed = RuleFrontmatter::parse_doc(&doc, artifact_root).map_err(|e| materialize_failed(e.to_string()))?;
        let rendered = self
            .vendor()
            .rule_index(&parsed, scope, pinned)
            .map_err(|e| materialize_failed(e.to_string()))?;

        let mut out = match rendered {
            // Canonical bytes are what this vendor reads — verbatim copy.
            None => {
                atomic_write(dest, &bytes).map_err(|e| target_io(dest, e))?;
                vec![MaterializedFile {
                    path: dest.to_path_buf(),
                    generated: false,
                }]
            }
            Some(rendered) => {
                for warning in &rendered.warnings {
                    tracing::warn!("{warning}");
                }
                atomic_write(dest, rendered.document.as_bytes()).map_err(|e| target_io(dest, e))?;
                vec![MaterializedFile {
                    path: dest.to_path_buf(),
                    generated: true,
                }]
            }
        };

        // Copy the sibling support tree verbatim (all clients, no transform)
        // beside the index at `<dest_parent>/<name>/`, so the index's
        // relative links resolve.
        if let Some(src) = support_dir
            && let Some(parent) = dest.parent()
        {
            copy_tree(src, &parent.join(name), &mut out)?;
        }

        out.sort_by(|a, b| a.path.cmp(&b.path));
        Ok(out)
    }

    /// Materialize an agent: the single file goes through the vendor's
    /// [`Vendor::agent_index`] transform (`None` ⇒ verbatim copy). Agents
    /// have no support directory. An unparseable agent document is a
    /// materialize failure — unlike a rule, the frontmatter is required.
    fn materialize_agent(
        self,
        artifact_root: &Path,
        dest: &Path,
        pinned: &str,
    ) -> Result<Vec<MaterializedFile>, InstallError> {
        let bytes = std::fs::read(artifact_root).map_err(|e| target_io(artifact_root, e))?;
        if let Some(parent) = dest.parent() {
            std::fs::create_dir_all(parent).map_err(|e| target_io(parent, e))?;
        }

        let doc = String::from_utf8_lossy(&bytes);
        let parsed = AgentFrontmatter::parse_doc(&doc, artifact_root).map_err(|e| materialize_failed(e.to_string()))?;
        let rendered = self
            .vendor()
            .agent_index(&parsed, pinned)
            .map_err(|e| materialize_failed(e.to_string()))?;

        let out = match rendered {
            // Canonical bytes are what this vendor reads — verbatim copy.
            None => {
                atomic_write(dest, &bytes).map_err(|e| target_io(dest, e))?;
                vec![MaterializedFile {
                    path: dest.to_path_buf(),
                    generated: false,
                }]
            }
            Some(rendered) => {
                for warning in &rendered.warnings {
                    tracing::warn!("{warning}");
                }
                atomic_write(dest, rendered.document.as_bytes()).map_err(|e| target_io(dest, e))?;
                vec![MaterializedFile {
                    path: dest.to_path_buf(),
                    generated: true,
                }]
            }
        };
        Ok(out)
    }

    /// Materialize a hook payload: the canonical tree, copied **verbatim**,
    /// with no per-client transform and no generated file (S-003).
    ///
    /// # Why this takes no `self`
    ///
    /// The payload is client-independent by construction. Decision L records
    /// that one dispatcher serves every hook and that a registration is never
    /// itself recorded, so what a client-specific render could differ *in* —
    /// the event spelling, the matcher dialect, the command string — all lives
    /// in the registration ([`Vendor::hook_registration`]), not in the tree on
    /// disk. Taking `self` would invite a future per-client branch here, and a
    /// per-client payload would fork the one destination the prune refcount and
    /// the installer's dest-dedup both key on (C-020).
    ///
    /// Called once per `(client, scope)` by the installer onto the **same**
    /// `dest`, so it must be idempotent: [`copy_tree`] overwrites in place and
    /// creates missing parents, which makes a second call over an identical
    /// tree a no-op in content terms.
    ///
    /// # Every file is `generated: false`
    ///
    /// Nothing is rendered, so the integrity hash anchors on the canonical
    /// bytes and an author edit inside the payload reads as ordinary drift —
    /// which is the whole of C-009's tamper-*evidence* leg (the runtime hashes
    /// nothing; `ClientOutput::content_hash` surfaces payload drift at the next
    /// `grim status` or install).
    ///
    /// # The exec bit is never load-bearing (C-019)
    ///
    /// A payload fetched through OCI arrives `0o644`, so this deliberately does
    /// **not** chmod anything: `grim build` rejects a handler whose first token
    /// resolves to a payload-relative file, which is what makes the interpreter
    /// form the only shape and the mode a non-issue. `copy_tree` preserves
    /// whatever mode the canonical tree carried; it never adds one.
    ///
    /// # Errors
    ///
    /// [`InstallErrorKind::TargetIo`] for a filesystem failure. There is no
    /// parse step and therefore no `MaterializeFailed` path — the manifest was
    /// validated at `grim build` and is copied here as data.
    fn materialize_hook(artifact_root: &Path, dest: &Path) -> Result<Vec<MaterializedFile>, InstallError> {
        let mut out = Vec::new();
        copy_tree(artifact_root, dest, &mut out)?;
        out.sort_by(|a, b| a.path.cmp(&b.path));
        Ok(out)
    }
}

/// The absolute launcher path the [`hook_matrix_cell`] probes carry.
///
/// A matrix cell is a **documentation** question, so it must not depend on a
/// resolved `$GRIM_HOME` — this stands in for one. It is safe because the whole
/// refusal order of [`Vendor::hook_registration`] (surface → surface shape →
/// event → tier → decision K → matcher) is launcher-blind: the launcher reaches
/// the command *string* and nothing else, in the `Ok` arm every refusal returns
/// before. The test below pins that by computing the cell with two different
/// launcher paths and asserting the answers are equal; if a future refusal ever
/// inspects the launcher, that test fails rather than the doc column silently
/// becoming environment-dependent.
const HOOK_CELL_PROBE_LAUNCHER: &str = "/grim-home/hooks/bin/grim-hook";

/// The absolute dispatch-table path the [`hook_matrix_cell`] probes carry.
///
/// Same standing and same argument as [`HOOK_CELL_PROBE_LAUNCHER`]: the table is
/// located by argv (B1) and reaches only the command string, so the refusal order
/// never reads it, and the one equality test covers launcher, table and root
/// token together.
const HOOK_CELL_PROBE_TABLE: &str = "/grim-home/hooks/dispatch.json";

/// The matcher forms [`hook_matrix_cell`] probes each `(event, tier)` pair
/// with — a closed set, and a pair counts as armed when **any** entry arms it.
///
/// Two entries, because the set exists to separate a **matcher-specific**
/// refusal from a **client-wide** one, and one entry alone cannot:
///
/// - `Some("Read")` — one exact, translatable, non-shell-command tool name.
///   Deliberately absent from [`SHELL_COMMAND_TOOLS`](super::vendor) for every
///   client and `MatcherForm::ExactOrAlternation`, the identity translation into
///   all three v1 dialects, so it exercises the arming path.
/// - `None` — match-all, the most common authored form. Decision K's predicate
///   is conservative, so a match-all `mutator` *could* select a shell-command
///   tool and is refused
///   ([`HookDecline::MutatorOnShellCommandTool`](super::vendor::HookDecline::MutatorOnShellCommandTool)).
///
/// **Any-arms, not all-arms, and that is the whole point of two entries.**
/// Decision K refuses a `(tool, matcher)`, never a client — so a client whose
/// `mutator` arms for `Read` and declines for `*` *has* the tier, and the
/// refusal the author actually hits is reported per hook through the `Declined`
/// path (S-013), which is where a per-matcher fact belongs. Requiring every
/// probe to arm would let Decision K alone drag claude and codex to `◐` and
/// make the column say "partial hook support" about a per-matcher security
/// refusal. A decline that holds for **both** probes is matcher-independent —
/// a projection-table gap — and that is what degrades the cell.
const HOOK_CELL_PROBE_MATCHERS: [Option<&str>; 2] = [Some("Read"), None];

/// The `docs/src/clients.md` **Hook** cell for `client` (C-013).
///
/// One helper, one column, computed from code so the matrix can never assert
/// hook support in prose. WP-L reads it from the parity test and maps it the
/// way every other column is mapped: [`KindSupport::Native`] ⇒ `✓`,
/// [`Degraded`](KindSupport::Degraded) ⇒ `◐`,
/// [`Declined`](KindSupport::Declined) ⇒ `✗`.
///
/// # The verdict is read off `hook_registration`, and off nothing else
///
/// This is the whole reason the helper is not a one-line delegation.
/// [`Vendor::hook_tier_support`] is tool- and matcher-blind, so
/// `hook_tier_support(Mutator, PreToolUse)` answers `Native` on claude, codex
/// and copilot **while the registration for a shell-command matcher declines**
/// (ADR decision K, per `(tool, matcher)`). Both answers are correct at their
/// own granularity, and a cell filled from the capability question alone would
/// show a mutator as available where nothing is registered — the S-013
/// silent-guardrail report this contract exists to prevent. Arming is
/// [`Vendor::hook_registration`]'s answer, and it already consults
/// `hook_tier_support` inside its own refusal order
/// ([`TierUnsupported`](super::vendor::HookDecline::TierUnsupported)), so every
/// projection-table gap still reaches the cell — through one authority instead
/// of two.
///
/// # An absent `context` column is **not** a cell degrader
///
/// Read this before re-deriving the rule; the opposite reading is the easy
/// mistake and it produces a matrix with zero `✓`. `additionalContext` has
/// **no tier owner**, so its absence costs no tier anything it was entitled to:
///
/// - [`Observer`](crate::oci::hook::HookTier::Observer) is defined as a tier
///   whose *"response cannot change what happens"*. Injecting context changes
///   what the model subsequently sees, so an observer emitting it would
///   contradict its own tier definition.
/// - [`Gatekeeper`](crate::oci::hook::HookTier::Gatekeeper)'s power is the
///   verdict; [`Mutator`](crate::oci::hook::HookTier::Mutator)'s is
///   `updatedInput`.
///
/// The channel's one owner is **mutator control 5, visible-to-model** (S-016: a
/// mutator's rewrite is also surfaced to the model). `mutator` is valid only at
/// `PreToolUse`, and all three v1 clients carry `context: Some(_)` there — so
/// the capability that genuinely needs the channel has it exactly where it is
/// needed, and `context: None` at `Stop` / `SessionStart` denies nothing.
/// `hook_tier_support`'s `Degraded` therefore has no bearing on this cell.
///
/// # The aggregation rule, stated so a test can be generated from it
///
/// 1. The probe set is the `(event, tier)` pairs of
///    [`CanonicalEvent::ALL`](crate::oci::hook::CanonicalEvent::ALL) ×
///    [`HookTier::ALL`](crate::oci::hook::HookTier::ALL) that
///    [`HookTier::is_valid_at`](crate::oci::hook::HookTier::is_valid_at)
///    admits — `mutator` only at `PreToolUse`, `gatekeeper` only on a
///    verdict-admitting event. Scoping to *declarable* tiers is ADR C-013's own
///    correction: without it the cell asks about combinations `grim build`
///    rejects, and no client could ever reach `✓`. A tier not declarable at an
///    event never degrades the cell — notably `verdict: &[]` at `SessionStart`,
///    where **no** client admits a verdict, so gatekeeper is simply not a
///    question there.
/// 2. A pair **arms** when at least one [`HOOK_CELL_PROBE_MATCHERS`] entry
///    returns `Ok`; it is `Declined` only when every entry returns `Err` — see
///    that constant for why any-arms is the correct quantifier.
/// 3. The cell is `✓` when every declarable pair arms, `◐` when some but not
///    all do, `✗` when none do.
///
/// Only a **decline of a tier declarable at that event** degrades a cell. On the
/// shipped table that makes claude and codex `✓`, and copilot `◐` — driven by
/// `verdict: &[]` at `PostToolUse`, where gatekeeper *is* declarable because
/// claude and codex both block there.
///
/// # Two things the cell deliberately does not say
///
/// - **It is scope-blind.** codex and copilot arm at global scope only
///   (`SCOPE_GAPS`, ADR amendment A1); the cell does not encode that, exactly as
///   the Rule column does not encode Junie's missing global surface. Both are
///   Known-gaps prose (WP-L / WP-M), not a fourth cell value.
/// - **It says nothing about whether hooks are *enabled*.** The experimental
///   flag and the registry-trust gate are install-time consent, not client
///   capability.
///
/// # Why `root` is a parameter and not minted here
///
/// [`RootToken`] has **no constructor** — by design, and the design is the point:
/// a token any caller could build from a `&str` would be exactly as forgeable as
/// the absolute path it replaced (B3). The only way to obtain one is
/// [`hook_dispatch::root_token`](super::hook_dispatch::root_token), whose HMAC
/// derivation reads or creates the machine key under a **real** `$GRIM_HOME` — so
/// a documentation-matrix helper cannot mint its own without either doing
/// filesystem I/O or acquiring a test-only bypass that would re-open what
/// deleting the placeholder token closed. Taking it as a parameter is the third
/// option and the honest one: the caller already has a `$GRIM_HOME` in every real
/// consumer (WP-H's status cell runs inside a grim process; WP-L's parity test
/// derives one in a temp dir), and the value provably cannot change the answer —
/// which is exactly what [`hook_cell_probe_independence`](self) asserts.
///
/// # Fail-safe half, and the only half that holds without the projection table
///
/// A client with no surface answers `Declined` before anything else is consulted
/// — 15 of 18 clients. Same split, and the same reason, as
/// [`Vendor::hook_tier_support`]'s.
// `allow`, not the Stub phase's `expect`, and the choice is forced: the
// fail-safe-half test below calls this, so in the **test** target an `expect` is
// unfulfilled and rejected, while in the **bin** target — where no production
// caller exists yet — its absence is a `dead_code` error. Only `allow`
// satisfies both. `allow` is inert, so the obligation is restated here where a
// reader will see it: **WP-L's `clients.md` parity test must call this**, or the
// doc column is asserted in prose, which is exactly what C-013 forbids. The two
// probe constants and the two helpers below ride on this attribute as live roots.
#[allow(
    dead_code,
    reason = "the production consumers are WP-L's clients.md parity test and WP-H's status cell"
)]
pub fn hook_matrix_cell(client: ClientTarget, root: &RootToken) -> KindSupport {
    let vendor = client.vendor();
    if vendor.declines_hooks_everywhere() {
        return KindSupport::Declined;
    }
    // Rules 1 and 3. `declarable` is never zero — `observer` is valid at every
    // event — so the `armed == declarable` arm cannot be reached vacuously.
    let mut declarable = 0usize;
    let mut armed = 0usize;
    for event in CanonicalEvent::ALL {
        for tier in HookTier::ALL {
            if !tier.is_valid_at(event) {
                continue;
            }
            declarable += 1;
            // Rule 2: any-arms, never all-arms — see HOOK_CELL_PROBE_MATCHERS.
            if HOOK_CELL_PROBE_MATCHERS
                .iter()
                .any(|matcher| hook_cell_probe_arms(vendor, event, tier, *matcher, root))
            {
                armed += 1;
            }
        }
    }
    match armed {
        0 => KindSupport::Declined,
        n if n == declarable => KindSupport::Native,
        _ => KindSupport::Degraded,
    }
}

/// Whether `(event, tier, matcher)` **registers** on `vendor` — one probe of
/// [`hook_matrix_cell`]'s aggregation, and the only place the cell touches the
/// arming authority.
///
/// `Ok` is the whole verdict: the registration either assembles or names a
/// [`HookDecline`](super::vendor::HookDecline). The reason is deliberately
/// dropped here — a cell has three values, and *which* refusal fired is the
/// per-hook S-013 report's job, not the doc column's.
fn hook_cell_probe_arms(
    vendor: &dyn Vendor,
    event: CanonicalEvent,
    tier: HookTier,
    matcher: Option<&str>,
    root: &RootToken,
) -> bool {
    vendor
        .hook_registration(
            &hook_cell_probe_entry(tier, matcher),
            event,
            Path::new(HOOK_CELL_PROBE_LAUNCHER),
            Path::new(HOOK_CELL_PROBE_TABLE),
            root,
        )
        .is_ok()
}

/// The throwaway [`HookEntry`] one [`hook_cell_probe_arms`] probe registers.
///
/// Every field outside `(tier, matcher)` is a fixed, translation-neutral filler:
/// the refusal order reads `tier` and `matcher` and nothing else off the entry,
/// so a probe that varied `id`, `handler`, `timeout` or the vendor overrides
/// would be asserting the *absence* of an influence in a way the two-launcher
/// equality test already covers for the launcher.
fn hook_cell_probe_entry(tier: HookTier, matcher: Option<&str>) -> HookEntry {
    HookEntry {
        id: "grim-matrix-probe".to_string(),
        // `None`: the probed event is passed to `hook_registration` directly, and
        // a `<vendor>.event` override is exactly the per-client special case a
        // matrix cell must not encode.
        event: None,
        tier,
        matcher: matcher.map(str::to_string),
        handler: HookHandler::Command("true".to_string()),
        timeout: None,
        payload: None,
        policy: None,
        vendor: std::collections::BTreeMap::new(),
    }
}

fn materialize_failed(msg: String) -> InstallError {
    InstallError::without_reference(InstallErrorKind::MaterializeFailed(msg))
}

/// Recursively copy every regular file under `src` into `dst`, preserving
/// the relative structure. Records each written file as a canonical
/// (non-generated) [`MaterializedFile`].
fn copy_tree(src: &Path, dst: &Path, out: &mut Vec<MaterializedFile>) -> Result<(), InstallError> {
    let meta = std::fs::symlink_metadata(src).map_err(|e| target_io(src, e))?;
    if meta.is_dir() {
        std::fs::create_dir_all(dst).map_err(|e| target_io(dst, e))?;
        let mut children: Vec<PathBuf> = std::fs::read_dir(src)
            .map_err(|e| target_io(src, e))?
            .map(|e| e.map(|e| e.path()))
            .collect::<std::io::Result<Vec<_>>>()
            .map_err(|e| target_io(src, e))?;
        children.sort();
        for child in children {
            let name = child.file_name().unwrap_or_default();
            copy_tree(&child, &dst.join(name), out)?;
        }
    } else if meta.is_file() {
        if let Some(parent) = dst.parent() {
            std::fs::create_dir_all(parent).map_err(|e| target_io(parent, e))?;
        }
        atomic_copy(src, dst).map_err(|e| target_io(dst, e))?;
        out.push(MaterializedFile {
            path: dst.to_path_buf(),
            generated: false,
        });
    }
    Ok(())
}

/// Copy `src` onto `dst` through a sibling temp file, so an interrupted copy
/// leaves the previous destination in place instead of a truncated one.
///
/// [`atomic_write`] is the equivalent for generated text, but it caps the
/// mode at `0o644`: a skill tree carries executable scripts, and copying
/// verbatim has to mean the permission bits too. `std::fs::copy` applies the
/// source's bits to the file it writes, so the mode rides along to the temp
/// and survives the rename.
fn atomic_copy(src: &Path, dst: &Path) -> std::io::Result<()> {
    let parent = dst.parent().unwrap_or_else(|| Path::new("."));
    // `tempfile_in` creates with `O_EXCL`, and everything below works through
    // that open handle rather than re-opening the temp by name — so nothing
    // here can be redirected by a file (or symlink) planted at the path
    // between creation and use. Reaching for `std::fs::copy` on the temp path
    // would give up both properties.
    let tmp = tempfile::Builder::new().prefix(".grim-tmp-").tempfile_in(parent)?;
    let mut source = std::fs::File::open(src)?;
    std::io::copy(&mut source, &mut tmp.as_file())?;
    // `std::fs::copy` would have carried the mode; doing it by hand keeps the
    // executable bit on a skill's scripts, which is what makes this helper
    // exist instead of `atomic_write`.
    tmp.as_file().set_permissions(source.metadata()?.permissions())?;
    tmp.persist(dst).map_err(|e| e.error)?;
    Ok(())
}

fn target_io(path: &Path, source: std::io::Error) -> InstallError {
    InstallError::without_reference(InstallErrorKind::TargetIo {
        path: path.to_path_buf(),
        source,
    })
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::config::scope::ConfigScope;
    use std::str::FromStr;

    #[test]
    fn value_names_match_all_and_round_trip() {
        assert_eq!(ClientTarget::VALUE_NAMES.len(), ClientTarget::ALL.len());
        for (name, target) in ClientTarget::VALUE_NAMES.iter().zip(ClientTarget::ALL) {
            assert_eq!(ClientTarget::from_str(name).unwrap(), target);
        }
    }

    // ── kind_support grid + G4 parity tests (adr_client_compat_matrix) ──

    /// Full vendor × kind grid asserted against the `adr_vendor_wave_expansion`
    /// §1 mapping table: Skill/Rule/Agent via [`Vendor::kind_support`], MCP via
    /// the boolean [`Vendor::mcp_config_path`] surface.
    #[test]
    fn kind_support_grid_matches_adr_mapping_table() {
        use crate::install::vendor::KindSupport::{Declined, Degraded, Native};
        // (client, Skill, Rule, Agent, has-MCP-surface). Every real vendor
        // exposes an MCP config surface; the generic `agents` client is the one
        // target with none — there is no vendor-neutral MCP config location.
        let grid = [
            (ClientTarget::Claude, Native, Native, Native, true),
            (ClientTarget::OpenCode, Native, Degraded, Native, true),
            (ClientTarget::Copilot, Native, Native, Native, true),
            (ClientTarget::Codex, Native, Declined, Native, true),
            (ClientTarget::Cursor, Native, Native, Native, true),
            (ClientTarget::Kiro, Native, Native, Declined, true),
            // Junie: rules Degraded — `.junie/rules/*.md` is ownable but every
            // file in it is concatenated, so `paths` is dropped. Project scope
            // only; the global half is gated by `Vendor::kind_surface`.
            (ClientTarget::Junie, Native, Degraded, Declined, true),
            (ClientTarget::Gemini, Native, Declined, Native, true),
            (ClientTarget::Zed, Native, Declined, Declined, true),
            (ClientTarget::Amp, Native, Declined, Declined, true),
            (ClientTarget::Agents, Native, Declined, Declined, false),
            // Antigravity: rules declined (global rules are a monolithic
            // ~/.gemini/GEMINI.md shared with Gemini CLI).
            (ClientTarget::Antigravity, Native, Declined, Native, true),
            // The wave-2 skills-only batch: every one declines Rule, Agent and
            // MCP, so each has no MCP config surface either.
            (ClientTarget::Cline, Native, Declined, Declined, false),
            (ClientTarget::Droid, Native, Declined, Declined, false),
            (ClientTarget::Goose, Native, Declined, Declined, false),
            (ClientTarget::Warp, Native, Declined, Declined, false),
            (ClientTarget::OpenClaw, Native, Declined, Declined, false),
            (ClientTarget::Kilo, Native, Declined, Declined, false),
        ];
        assert_eq!(
            grid.len(),
            ClientTarget::ALL.len(),
            "grid must cover every ClientTarget"
        );
        let project = crate::config::scope::ConfigScope::Project;
        for (client, skill, rule, agent, has_mcp) in grid {
            let v = client.vendor();
            assert_eq!(v.kind_support(ArtifactKind::Skill), skill, "{client} skill");
            assert_eq!(v.kind_support(ArtifactKind::Rule), rule, "{client} rule");
            assert_eq!(v.kind_support(ArtifactKind::Agent), agent, "{client} agent");
            assert_eq!(
                v.mcp_config_path(Path::new("/w"), project).is_some(),
                has_mcp,
                "{client} MCP config surface must match the grid"
            );
            // The two MCP signals must agree: a vendor with no config path
            // must also decline the kind, so the installer skips it at the
            // `kind_support` gate rather than resolving a phantom target.
            assert_eq!(
                v.kind_support(ArtifactKind::Mcp) != Declined,
                has_mcp,
                "{client} kind_support(Mcp) must track mcp_config_path"
            );
        }
    }

    /// A documented support-matrix cell.
    #[derive(PartialEq, Eq, Clone, Copy, Debug)]
    enum Cell {
        Yes,     // ✓
        Partial, // ◐
        No,      // ✗
    }

    /// Parse the first markdown table of a docs page into `(client, [Skill,
    /// Rule, Agent, MCP, Hook])` rows. Cell parsing keys on the `✓`/`◐`/`✗`
    /// token only, whitespace- and formatting-insensitive; an unrecognized cell
    /// (e.g. a `TODO` placeholder) is a `None` that fails the caller's assert.
    ///
    /// A **missing** column is the same `None` as an unrecognized token: cells
    /// are read through `Vec::get`, so a row that stops short (a five-cell row
    /// against a six-column matrix) still lands in the returned set and fails
    /// the caller's placeholder assert by name. Dropping the row instead would
    /// fail the row-set equality assert with a message about the row set, which
    /// says nothing about the column that went missing.
    fn parse_first_matrix(md: &str) -> Vec<(String, [Option<Cell>; 5])> {
        let mut rows = Vec::new();
        let mut in_table = false;
        for line in md.lines() {
            let line = line.trim();
            if !line.starts_with('|') {
                if in_table {
                    break; // table ended
                }
                continue;
            }
            in_table = true;
            let cells: Vec<&str> = line.trim_matches('|').split('|').map(str::trim).collect();
            // Separator row (|----|----|).
            if cells
                .iter()
                .all(|c| !c.is_empty() && c.chars().all(|ch| ch == '-' || ch == ':'))
            {
                continue;
            }
            // Header row (first cell is the literal "Client").
            if cells.first().is_some_and(|c| c.eq_ignore_ascii_case("Client")) {
                continue;
            }
            if cells.len() < 5 {
                continue;
            }
            // The client cell leads with an inline mark (`<svg …>`, or a
            // lettered `<span>` for a client no icon set carries) and then a
            // hyperlink (`[Claude]`, `[Claude][claude]`, or `[Claude](url)`) —
            // reduce it to the link text before matching.
            let raw = cells[0];
            let name = raw
                .split_once('[')
                .map(|(_, rest)| rest)
                .and_then(|r| r.split_once(']'))
                .map_or(raw, |(text, _)| text)
                .to_ascii_lowercase();
            let cell = |idx: usize| match cells.get(idx) {
                Some(c) if c.contains('✓') => Some(Cell::Yes),
                Some(c) if c.contains('◐') => Some(Cell::Partial),
                Some(c) if c.contains('✗') => Some(Cell::No),
                _ => None,
            };
            rows.push((name, [cell(1), cell(2), cell(3), cell(4), cell(5)]));
        }
        rows
    }

    /// Table-parity: reads `docs/src/clients.md` at TEST RUNTIME (not compile
    /// time — `std::fs::read_to_string` below), parses the
    /// first markdown table, and asserts for every `(client, kind)` that a
    /// documented `✗` ⇔ `kind_support == Declined` (MCP: `mcp_config_path` is
    /// `None`), `◐` ⇔ `Degraded` (rule column), `✓` ⇔ `Native`, and the row
    /// set equals `ClientTarget::ALL` exactly.
    ///
    /// The **Hook** column is the one cell with a different authority:
    /// [`hook_matrix_cell`], not `kind_support` — see the assert below.
    #[test]
    fn docs_matrix_row_set_matches_all_and_cells_track_kind_support() {
        use crate::install::vendor::KindSupport;
        let md = std::fs::read_to_string(concat!(env!("CARGO_MANIFEST_DIR"), "/docs/src/clients.md"))
            .expect("docs/src/clients.md exists (matrix parity)");
        let rows = parse_first_matrix(&md);
        // The Hook cell's only input besides the client. Provably cannot change
        // the answer (`hook_cell_probe_independence`), but the type has no
        // constructor, so the test derives a real one in a temp `$GRIM_HOME`.
        let (root, _tmp) = probe_root();

        let documented: std::collections::BTreeSet<&str> = rows.iter().map(|(n, _)| n.as_str()).collect();
        let expected: std::collections::BTreeSet<&str> = ClientTarget::ALL.iter().map(|c| c.as_str()).collect();
        assert_eq!(
            documented, expected,
            "clients.md row set must equal ClientTarget::ALL exactly"
        );

        let project = crate::config::scope::ConfigScope::Project;
        for (name, cells) in &rows {
            let client: ClientTarget = name.parse().unwrap_or_else(|_| panic!("unknown client row '{name}'"));
            let v = client.vendor();
            for (idx, kind) in [ArtifactKind::Skill, ArtifactKind::Rule, ArtifactKind::Agent]
                .into_iter()
                .enumerate()
            {
                let cell =
                    cells[idx].unwrap_or_else(|| panic!("unparsed {kind:?} cell for '{name}' (TODO placeholder?)"));
                let expected = match v.kind_support(kind) {
                    KindSupport::Native => Cell::Yes,
                    KindSupport::Degraded => Cell::Partial,
                    KindSupport::Declined => Cell::No,
                };
                assert_eq!(cell, expected, "{name} {kind:?} cell must track kind_support");
            }
            // MCP column: boolean surface — ✗ ⇔ no config path, ✓/◐ ⇔ some.
            let mcp = cells[3].unwrap_or_else(|| panic!("unparsed MCP cell for '{name}' (TODO placeholder?)"));
            let supported = v.mcp_config_path(Path::new("/w"), project).is_some();
            assert_eq!(mcp != Cell::No, supported, "{name} MCP cell must track mcp_config_path");
            // Hook column: its own authority. It CANNOT join the enumerate loop
            // above, because Hook is not `kind_support`-driven —
            // `hook_matrix_cell` aggregates `Vendor::hook_registration` over the
            // declarable `(event, tier)` pairs, which is the whole reason a
            // dedicated helper exists (C-013). Mapped like every other column.
            let hook = cells[4].unwrap_or_else(|| panic!("unparsed Hook cell for '{name}' (TODO placeholder?)"));
            let expected = match hook_matrix_cell(client, &root) {
                KindSupport::Native => Cell::Yes,
                KindSupport::Degraded => Cell::Partial,
                KindSupport::Declined => Cell::No,
            };
            assert_eq!(hook, expected, "{name} Hook cell must track hook_matrix_cell");
        }
    }

    /// Scope `md` to the section starting at the `## …{anchor}` heading
    /// (heading to the next `## `), falling back to the whole document if
    /// the anchor is absent. Shared by every row-presence test below —
    /// each scopes a different doc's client-enumerating section with its
    /// own anchor.
    fn heading_section<'a>(md: &'a str, anchor: &str) -> &'a str {
        let Some(start) = md.find(anchor) else {
            return md;
        };
        let rest = &md[start..];
        match rest[1..].find("\n## ") {
            Some(end) => &rest[..end + 1],
            None => rest,
        }
    }

    /// Whether `word` occurs in `haystack` delimited by non-alphanumeric
    /// boundaries — so a client name like `zed`/`amp` matches its own table
    /// cell or `[zed]` link but not a substring of prose (`materialized`,
    /// `example`). Both args are already lowercased by the callers. Without
    /// this the row-presence guards below could silently go vacuous the day
    /// a section gains such a word.
    fn contains_word(haystack: &str, word: &str) -> bool {
        let boundary = |c: Option<char>| c.is_none_or(|c| !c.is_ascii_alphanumeric());
        haystack.match_indices(word).any(|(i, _)| {
            boundary(haystack[..i].chars().next_back()) && boundary(haystack[i + word.len()..].chars().next())
        })
    }

    /// Emit-matrix row-presence: every `ClientTarget` name appears in the
    /// `docs/src/agents.md` emit-matrix section (catches "added a vendor,
    /// forgot the emit matrix" without over-constraining prose).
    #[test]
    fn agents_emit_matrix_lists_every_client() {
        let md = std::fs::read_to_string(concat!(env!("CARGO_MANIFEST_DIR"), "/docs/src/agents.md"))
            .expect("docs/src/agents.md exists");
        let section = heading_section(&md, "{#emit-matrix}").to_ascii_lowercase();
        for client in ClientTarget::ALL {
            assert!(
                contains_word(&section, client.as_str()),
                "agents.md emit matrix must list every client — missing '{client}'"
            );
        }
    }

    /// Emit-matrix row-presence for `docs/src/mcp-servers.md` — same
    /// invariant as [`agents_emit_matrix_lists_every_client`].
    #[test]
    fn mcp_servers_emit_matrix_lists_every_client() {
        let md = std::fs::read_to_string(concat!(env!("CARGO_MANIFEST_DIR"), "/docs/src/mcp-servers.md"))
            .expect("docs/src/mcp-servers.md exists");
        let section = heading_section(&md, "{#emit-matrix}").to_ascii_lowercase();
        for client in ClientTarget::ALL {
            assert!(
                contains_word(&section, client.as_str()),
                "mcp-servers.md emit matrix must list every client — missing '{client}'"
            );
        }
    }

    /// Row-presence for `docs/src/vendor-metadata.md`'s
    /// `{#discovery-locations}` section (both the project- and
    /// global-scope tables): every `ClientTarget` must appear — skill
    /// discovery is `Native` for all ten, so there is no subset to carve
    /// out (contrast the two tests below, which are Rule/Agent-scoped).
    #[test]
    fn vendor_metadata_discovery_locations_lists_every_client() {
        let md = std::fs::read_to_string(concat!(env!("CARGO_MANIFEST_DIR"), "/docs/src/vendor-metadata.md"))
            .expect("docs/src/vendor-metadata.md exists");
        let section = heading_section(&md, "{#discovery-locations}").to_ascii_lowercase();
        for client in ClientTarget::ALL {
            assert!(
                contains_word(&section, client.as_str()),
                "vendor-metadata.md discovery-locations section must list every client — missing '{client}'"
            );
        }
    }

    /// Row-presence for `docs/src/vendor-metadata.md`'s `{#rule-keys}`
    /// section, scoped to clients that do **not** decline the Rule kind.
    /// The table documents per-client rule-frontmatter field mapping (or,
    /// for Codex, an explicit unsupported note) — the remaining declined
    /// clients (Junie, Gemini, Zed, Amp) have no rule surface to map and
    /// are not required here; their decline is already machine-checked by
    /// [`kind_support_grid_matches_adr_mapping_table`] and the
    /// `clients.md` compat matrix.
    #[test]
    fn vendor_metadata_rule_keys_lists_every_rule_capable_client() {
        use crate::install::vendor::KindSupport;
        let md = std::fs::read_to_string(concat!(env!("CARGO_MANIFEST_DIR"), "/docs/src/vendor-metadata.md"))
            .expect("docs/src/vendor-metadata.md exists");
        let section = heading_section(&md, "{#rule-keys}").to_ascii_lowercase();
        for client in ClientTarget::ALL {
            if client.vendor().kind_support(ArtifactKind::Rule) == KindSupport::Declined {
                continue;
            }
            assert!(
                contains_word(&section, client.as_str()),
                "vendor-metadata.md rule-keys section must list every rule-capable client — missing '{client}'"
            );
        }
    }

    /// Row-presence for `docs/src/agents.md`'s `{#locations}` section,
    /// scoped to clients that do **not** decline the Agent kind — mirrors
    /// [`vendor_metadata_rule_keys_lists_every_rule_capable_client`]: the
    /// four declined clients (Kiro, Junie, Zed, Amp) have no install path
    /// to list, and are already covered by the `{#emit-matrix}` row-
    /// presence test above.
    #[test]
    fn agents_locations_lists_every_agent_capable_client() {
        use crate::install::vendor::KindSupport;
        let md = std::fs::read_to_string(concat!(env!("CARGO_MANIFEST_DIR"), "/docs/src/agents.md"))
            .expect("docs/src/agents.md exists");
        let section = heading_section(&md, "{#locations}").to_ascii_lowercase();
        for client in ClientTarget::ALL {
            if client.vendor().kind_support(ArtifactKind::Agent) == KindSupport::Declined {
                continue;
            }
            assert!(
                contains_word(&section, client.as_str()),
                "agents.md locations section must list every agent-capable client — missing '{client}'"
            );
        }
    }

    /// Row-presence for `docs/src/json-interface.md`'s `options.clients`
    /// `string-set` values list — the literal JSON array of client names
    /// in its `config list` shape description must list every
    /// `ClientTarget`. The paragraph carries no `{#anchor}` heading, so it
    /// is scoped by its own marker text to the next blank line (paragraph
    /// boundary) instead of [`heading_section`]'s `## ` boundary.
    #[test]
    fn json_interface_options_clients_values_lists_every_client() {
        let md = std::fs::read_to_string(concat!(env!("CARGO_MANIFEST_DIR"), "/docs/src/json-interface.md"))
            .expect("docs/src/json-interface.md exists");
        let marker = "`options.clients` is the one `string-set` key";
        let start = md
            .find(marker)
            .expect("json-interface.md must describe options.clients as a string-set key");
        let rest = &md[start..];
        let end = rest.find("\n\n").unwrap_or(rest.len());
        let section = rest[..end].to_ascii_lowercase();
        for client in ClientTarget::ALL {
            assert!(
                contains_word(&section, client.as_str()),
                "json-interface.md options.clients values list must list every client — missing '{client}'"
            );
        }
    }

    #[test]
    fn from_str_and_display_round_trip_lowercase() {
        for (s, t) in [
            ("claude", ClientTarget::Claude),
            ("opencode", ClientTarget::OpenCode),
            ("copilot", ClientTarget::Copilot),
            ("codex", ClientTarget::Codex),
            ("cursor", ClientTarget::Cursor),
            ("kiro", ClientTarget::Kiro),
            ("junie", ClientTarget::Junie),
            ("gemini", ClientTarget::Gemini),
            ("zed", ClientTarget::Zed),
            ("amp", ClientTarget::Amp),
            ("agents", ClientTarget::Agents),
            ("antigravity", ClientTarget::Antigravity),
            ("cline", ClientTarget::Cline),
            ("droid", ClientTarget::Droid),
            ("goose", ClientTarget::Goose),
            ("warp", ClientTarget::Warp),
            ("openclaw", ClientTarget::OpenClaw),
            ("kilo", ClientTarget::Kilo),
        ] {
            assert_eq!(ClientTarget::from_str(s).unwrap(), t);
            assert_eq!(t.to_string(), s);
        }
        assert!(ClientTarget::from_str("vscode").is_err());
        assert_eq!(ClientTarget::default(), ClientTarget::Claude);
    }

    /// Every client's project-scope layout, read from each vendor's
    /// `skills_root`/`rule_path`/`agent_path` source (`None` marks a kind
    /// the client declines — `kind_support == Declined` — so no on-disk
    /// output is ever written for it; the vendor still implements the
    /// trait method defensively, but that "dead path" is not asserted
    /// here). Iterates [`ClientTarget::ALL`] so a new vendor (#11) fails
    /// this test until its row is added — the array-length assert and the
    /// `kind_support` cross-check both make an incomplete table a build
    /// failure, not a silent gap.
    #[test]
    fn path_for_matches_each_client_layout() {
        use crate::install::vendor::KindSupport;

        let w = Path::new("/w");
        let project = crate::config::scope::ConfigScope::Project;

        let table: [(ClientTarget, &str, Option<&str>, Option<&str>); 18] = [
            (
                ClientTarget::Claude,
                ".claude/skills/x",
                Some(".claude/rules/x.md"),
                Some(".claude/agents/x.md"),
            ),
            (
                ClientTarget::OpenCode,
                ".opencode/skills/x",
                Some(".opencode/rules/x.md"),
                Some(".opencode/agents/x.md"),
            ),
            (
                ClientTarget::Copilot,
                ".github/skills/x",
                Some(".github/instructions/x.instructions.md"),
                Some(".github/agents/x.md"),
            ),
            // Codex: skills land in the cross-vendor `.agents/skills` tree
            // (not `.codex/skills`); agents are TOML under `.codex/agents`;
            // rules are declined.
            (
                ClientTarget::Codex,
                ".agents/skills/x",
                None,
                Some(".codex/agents/x.toml"),
            ),
            (
                ClientTarget::Cursor,
                ".cursor/skills/x",
                Some(".cursor/rules/x.mdc"),
                Some(".cursor/agents/x.md"),
            ),
            // Kiro: rules render as steering docs; agents declined.
            (ClientTarget::Kiro, ".kiro/skills/x", Some(".kiro/steering/x.md"), None),
            // Junie: skills + project-scope rules (degraded); agents declined.
            (ClientTarget::Junie, ".junie/skills/x", Some(".junie/rules/x.md"), None),
            // Gemini: skills via the shared pool; agents native; rules declined.
            (
                ClientTarget::Gemini,
                ".agents/skills/x",
                None,
                Some(".gemini/agents/x.md"),
            ),
            // Zed / Amp: skills via the shared pool only.
            (ClientTarget::Zed, ".agents/skills/x", None, None),
            (ClientTarget::Amp, ".agents/skills/x", None, None),
            // Generic client: the shared pool is its only surface.
            (ClientTarget::Agents, ".agents/skills/x", None, None),
            // Antigravity: project skills join the pool, agents sit beside
            // them under `.agents`; rules declined.
            (
                ClientTarget::Antigravity,
                ".agents/skills/x",
                None,
                Some(".agents/agents/x.md"),
            ),
            // Wave-2 batch: skills only, each in its own dir except Goose,
            // which renders to the shared pool at both scopes.
            (ClientTarget::Cline, ".cline/skills/x", None, None),
            // Droid's client name and directory deliberately differ.
            (ClientTarget::Droid, ".factory/skills/x", None, None),
            (ClientTarget::Goose, ".agents/skills/x", None, None),
            (ClientTarget::Warp, ".warp/skills/x", None, None),
            // OpenClaw has no project scope at all; this is its defensive dead
            // path, never an install destination (`kind_surface` refuses it).
            (ClientTarget::OpenClaw, ".openclaw/skills/x", None, None),
            (ClientTarget::Kilo, ".kilo/skills/x", None, None),
        ];
        assert_eq!(
            table.len(),
            ClientTarget::ALL.len(),
            "table must cover every ClientTarget"
        );

        for (client, skill, rule, agent) in table {
            assert_eq!(
                client.path_for(w, project, ArtifactKind::Skill, "x"),
                w.join(skill),
                "{client} skill path"
            );

            assert_eq!(
                rule.is_none(),
                client.vendor().kind_support(ArtifactKind::Rule) == KindSupport::Declined,
                "{client} rule table entry must track kind_support"
            );
            if let Some(rule) = rule {
                assert_eq!(
                    client.path_for(w, project, ArtifactKind::Rule, "x"),
                    w.join(rule),
                    "{client} rule path"
                );
            }

            assert_eq!(
                agent.is_none(),
                client.vendor().kind_support(ArtifactKind::Agent) == KindSupport::Declined,
                "{client} agent table entry must track kind_support"
            );
            if let Some(agent) = agent {
                assert_eq!(
                    client.path_for(w, project, ArtifactKind::Agent, "x"),
                    w.join(agent),
                    "{client} agent path"
                );
            }
        }
    }

    #[test]
    fn path_for_global_scope_uses_vendor_native_roots() {
        let w = Path::new("/grim-home");
        let g = crate::config::scope::ConfigScope::Global;
        // Native user-level discovery paths (resolvable in any env that
        // has $HOME — the fallback keeps the workspace layout otherwise).
        if let Some(home) = crate::install::vendor::home_dir() {
            assert_eq!(
                ClientTarget::Claude.path_for(w, g, ArtifactKind::Skill, "x"),
                home.join(".claude/skills/x")
            );
            assert_eq!(
                ClientTarget::Claude.path_for(w, g, ArtifactKind::Rule, "r"),
                home.join(".claude/rules/r.md")
            );
            assert_eq!(
                ClientTarget::Copilot.path_for(w, g, ArtifactKind::Skill, "x"),
                home.join(".copilot/skills/x")
            );
            // Codex skills follow the cross-vendor `$HOME/.agents/skills`
            // standard — NOT `$CODEX_HOME` (proven by the agent path below).
            assert_eq!(
                ClientTarget::Codex.path_for(w, g, ArtifactKind::Skill, "x"),
                home.join(".agents/skills/x")
            );
            // Antigravity is the one pool member whose GLOBAL skills are its
            // own: `~/.gemini/config/skills`, not `$HOME/.agents/skills` and
            // not `~/.gemini` (Gemini CLI's root). Its project skills DO join
            // the pool — asserted in `path_for_matches_each_client_layout`.
            assert_eq!(
                ClientTarget::Antigravity.path_for(w, g, ArtifactKind::Skill, "x"),
                home.join(".gemini/config/skills/x")
            );
            assert_eq!(
                ClientTarget::Antigravity.path_for(w, g, ArtifactKind::Agent, "rev"),
                home.join(".gemini/config/agents/rev.md")
            );
            // Codex agents live under `$CODEX_HOME|~/.codex` + `agents/`; the
            // env-override order is unit-tested in vendor_codex, so only assert
            // the `~/.codex` default when CODEX_HOME is unset.
            if crate::install::vendor::env_dir("CODEX_HOME").is_none() {
                assert_eq!(
                    ClientTarget::Codex.path_for(w, g, ArtifactKind::Agent, "rev"),
                    home.join(".codex/agents/rev.toml")
                );
            }
        }
        if let Some(cfg) = crate::install::vendor::xdg_config_dir() {
            assert_eq!(
                ClientTarget::OpenCode.path_for(w, g, ArtifactKind::Skill, "x"),
                cfg.join("opencode/skills/x")
            );
        }
        // OpenCode rules stay in the workspace layout (loaded via the
        // absolute instructions glob); Copilot rules route to the native
        // `$COPILOT_HOME|~/.copilot/instructions/` dir.
        assert_eq!(
            ClientTarget::OpenCode.path_for(w, g, ArtifactKind::Rule, "r"),
            PathBuf::from("/grim-home/.opencode/rules/r.md")
        );
        if let Some(home) = crate::install::vendor::home_dir()
            && crate::install::vendor::env_dir("COPILOT_HOME").is_none()
        {
            assert_eq!(
                ClientTarget::Copilot.path_for(w, g, ArtifactKind::Rule, "r"),
                home.join(".copilot/instructions/r.instructions.md")
            );
        }
    }

    /// Every destination write goes through a sibling temp + rename, so an
    /// interrupted one cannot leave a truncated file the untracked gate then
    /// refuses forever. Two properties that would break if a future change
    /// swapped the copy for `atomic_write` (mode capped at `0o644`) or left a
    /// temp behind (it would land in the footprint hash).
    #[cfg(unix)]
    #[test]
    fn materialize_skill_preserves_exec_bits_and_leaves_no_temp_files() {
        use std::os::unix::fs::PermissionsExt;

        let tmp = tempfile::tempdir().unwrap();
        let src = tmp.path().join("code-review");
        std::fs::create_dir_all(src.join("scripts")).unwrap();
        std::fs::write(src.join("SKILL.md"), "---\nname: code-review\n---\n# CR\n").unwrap();
        let script = src.join("scripts/run.sh");
        std::fs::write(&script, "#!/bin/sh\necho hi\n").unwrap();
        std::fs::set_permissions(&script, std::fs::Permissions::from_mode(0o755)).unwrap();

        let dest = tmp.path().join(".claude/skills/code-review");
        ClientTarget::Claude
            .materialize(MaterializeRequest {
                kind: ArtifactKind::Skill,
                name: "code-review",
                artifact_root: &src,
                dest: &dest,
                scope: ConfigScope::Project,
                pinned: "pin",
                support_dir: None,
            })
            .unwrap();

        let mode = std::fs::metadata(dest.join("scripts/run.sh"))
            .unwrap()
            .permissions()
            .mode();
        assert_eq!(
            mode & 0o111,
            0o111,
            "executable bits must survive the copy, got 0o{:o}",
            mode & 0o777
        );
        for dir in [&dest, &dest.join("scripts")] {
            let leftovers: Vec<_> = std::fs::read_dir(dir)
                .unwrap()
                .filter_map(|e| e.ok().map(|e| e.file_name()))
                .filter(|name| name.to_string_lossy().starts_with(".grim-tmp-"))
                .collect();
            assert!(
                leftovers.is_empty(),
                "temp files left in {}: {leftovers:?}",
                dir.display()
            );
        }
    }

    /// Writing through a temp + rename replaces a symlink at the destination
    /// instead of following it. The installer unlinks symlinked destinations
    /// before it materializes, so this only shows up on the `grim render`
    /// path, where the destination directory is the user's own and may hold
    /// anything — and there, landing the rule outside the directory the user
    /// named is never the intent.
    #[cfg(unix)]
    #[test]
    fn materialize_rule_replaces_a_symlinked_destination() {
        let tmp = tempfile::tempdir().unwrap();
        let src = tmp.path().join("rust-style.md");
        std::fs::write(&src, "---\npaths: [\"a\"]\n---\n# R\n").unwrap();
        let outside = tmp.path().join("outside.md");
        std::fs::write(&outside, "untouched\n").unwrap();
        let dest = tmp.path().join("render/rust-style.md");
        std::fs::create_dir_all(dest.parent().unwrap()).unwrap();
        std::os::unix::fs::symlink(&outside, &dest).unwrap();

        ClientTarget::Claude
            .materialize(MaterializeRequest {
                kind: ArtifactKind::Rule,
                name: "rust-style",
                artifact_root: &src,
                dest: &dest,
                scope: ConfigScope::Project,
                pinned: "p",
                support_dir: None,
            })
            .unwrap();

        assert_eq!(
            std::fs::read_to_string(&outside).unwrap(),
            "untouched\n",
            "the write must not follow the link out of the destination directory"
        );
        assert!(!dest.is_symlink(), "the link itself must be replaced");
        assert_eq!(
            std::fs::read_to_string(&dest).unwrap(),
            "---\npaths: [\"a\"]\n---\n# R\n"
        );
    }

    #[test]
    fn materialize_rule_claude_is_verbatim() {
        let tmp = tempfile::tempdir().unwrap();
        let src = tmp.path().join("rust-style.md");
        std::fs::write(&src, "---\npaths: [\"a\"]\n---\n# R\n").unwrap();
        let dest = tmp.path().join(".claude/rules/rust-style.md");
        let files = ClientTarget::Claude
            .materialize(MaterializeRequest {
                kind: ArtifactKind::Rule,
                name: "rust-style",
                artifact_root: &src,
                dest: &dest,
                scope: ConfigScope::Project,
                pinned: "p",
                support_dir: None,
            })
            .unwrap();
        assert_eq!(files.len(), 1);
        assert!(!files[0].generated);
        assert_eq!(
            std::fs::read_to_string(&dest).unwrap(),
            "---\npaths: [\"a\"]\n---\n# R\n"
        );
    }

    #[test]
    fn materialize_rule_copilot_is_generated_transform() {
        let tmp = tempfile::tempdir().unwrap();
        let src = tmp.path().join("rust-style.md");
        std::fs::write(&src, "---\npaths: [\"a\"]\n---\n# R\nbody\n").unwrap();
        let dest = tmp.path().join(".github/instructions/rust-style.instructions.md");
        let files = ClientTarget::Copilot
            .materialize(MaterializeRequest {
                kind: ArtifactKind::Rule,
                name: "rust-style",
                artifact_root: &src,
                dest: &dest,
                scope: ConfigScope::Project,
                pinned: "pin",
                support_dir: None,
            })
            .unwrap();
        assert!(files[0].generated);
        let body = std::fs::read_to_string(&dest).unwrap();
        assert!(body.starts_with("---\napplyTo: \"a\"\n---\n<!-- generated by grim from pin;"));
        assert!(!body.contains("paths:"));
    }

    #[test]
    fn materialize_rule_opencode_is_generated_body_only() {
        let tmp = tempfile::tempdir().unwrap();
        let src = tmp.path().join("rust-style.md");
        std::fs::write(&src, "---\npaths: [\"a\"]\n---\n# R\nbody\n").unwrap();
        let dest = tmp.path().join(".opencode/rules/rust-style.md");
        let files = ClientTarget::OpenCode
            .materialize(MaterializeRequest {
                kind: ArtifactKind::Rule,
                name: "rust-style",
                artifact_root: &src,
                dest: &dest,
                scope: ConfigScope::Project,
                pinned: "pin",
                support_dir: None,
            })
            .unwrap();
        assert!(files[0].generated);
        let body = std::fs::read_to_string(&dest).unwrap();
        assert!(body.starts_with("<!-- generated by grim from pin;"));
        assert!(!body.contains("paths:"), "frontmatter stripped for OpenCode");
    }

    #[test]
    fn materialize_rule_claude_with_vendor_metadata_is_generated_cleaned() {
        // Rule symmetry with skills: a rule carrying tool-namespaced
        // metadata is re-rendered for Claude too — foreign vendor keys do
        // not leak into `.claude/rules/`, the file is generated.
        let tmp = tempfile::tempdir().unwrap();
        let src = tmp.path().join("rust-style.md");
        std::fs::write(
            &src,
            "---\npaths: [\"**/*.rs\"]\nkeywords: rust\nmetadata:\n  copilot.exclude-agent: code-review\n---\n# R\nbody\n",
        )
        .unwrap();
        let dest = tmp.path().join(".claude/rules/rust-style.md");
        let files = ClientTarget::Claude
            .materialize(MaterializeRequest {
                kind: ArtifactKind::Rule,
                name: "rust-style",
                artifact_root: &src,
                dest: &dest,
                scope: ConfigScope::Project,
                pinned: "p",
                support_dir: None,
            })
            .unwrap();
        assert!(files[0].generated, "cleaned render is a generated file");
        let body = std::fs::read_to_string(&dest).unwrap();
        assert!(!body.contains("copilot.exclude-agent"), "foreign vendor key dropped");
        assert!(body.contains("**/*.rs"), "native paths scoping kept");
        assert!(body.contains("keywords: rust"), "plain catalog key kept");
        assert!(body.ends_with("# R\nbody\n"));
    }

    #[test]
    fn materialize_skill_copies_tree_verbatim_all_clients() {
        let tmp = tempfile::tempdir().unwrap();
        let root = tmp.path().join("code-review");
        std::fs::create_dir_all(root.join("scripts")).unwrap();
        std::fs::write(root.join("SKILL.md"), "---\nname: code-review\ndescription: d\n---\n").unwrap();
        std::fs::write(root.join("scripts/run.sh"), "echo hi\n").unwrap();

        // Every vendor's `skill_index` returns `None` (verbatim install) for
        // a doc carrying no vendor-namespaced metadata — the six vendor-aware
        // vendors via `render::render_skill_doc`, the four shared-pool vendors
        // via `render::render_universal_skill_doc` — so this fixture's fast
        // path is vendor-independent and must hold for all 10.
        for client in ClientTarget::ALL {
            let dest = tmp.path().join(format!("out-{client}/code-review"));
            let files = client
                .materialize(MaterializeRequest {
                    kind: ArtifactKind::Skill,
                    name: "code-review",
                    artifact_root: &root,
                    dest: &dest,
                    scope: ConfigScope::Project,
                    pinned: "p",
                    support_dir: None,
                })
                .unwrap();
            assert_eq!(files.len(), 2);
            assert!(files.iter().all(|f| !f.generated));
            assert_eq!(
                std::fs::read_to_string(dest.join("SKILL.md")).unwrap(),
                "---\nname: code-review\ndescription: d\n---\n"
            );
            assert_eq!(
                std::fs::read_to_string(dest.join("scripts/run.sh")).unwrap(),
                "echo hi\n"
            );
        }
    }

    #[test]
    fn materialize_rule_with_support_dir_claude_verbatim() {
        // The index lands verbatim (paths: is native) and the support tree
        // is copied beside it at `<dest_parent>/<name>/`.
        let tmp = tempfile::tempdir().unwrap();
        let src = tmp.path().join("my-rule.md");
        std::fs::write(&src, "---\npaths: [\"a\"]\n---\n# index\n").unwrap();
        let support = tmp.path().join("my-rule");
        std::fs::create_dir_all(support.join("nested")).unwrap();
        std::fs::write(support.join("examples.md"), "# ex\n").unwrap();
        std::fs::write(support.join("nested/schema.json"), "{}\n").unwrap();

        let dest = tmp.path().join(".claude/rules/my-rule.md");
        let files = ClientTarget::Claude
            .materialize(MaterializeRequest {
                kind: ArtifactKind::Rule,
                name: "my-rule",
                artifact_root: &src,
                dest: &dest,
                scope: ConfigScope::Project,
                pinned: "p",
                support_dir: Some(support.as_path()),
            })
            .unwrap();

        assert!(files.iter().all(|f| !f.generated), "verbatim copies are not generated");
        let support_dest = dest.parent().unwrap().join("my-rule");
        assert_eq!(
            std::fs::read_to_string(&dest).unwrap(),
            "---\npaths: [\"a\"]\n---\n# index\n"
        );
        assert_eq!(
            std::fs::read_to_string(support_dest.join("examples.md")).unwrap(),
            "# ex\n"
        );
        assert_eq!(
            std::fs::read_to_string(support_dest.join("nested/schema.json")).unwrap(),
            "{}\n"
        );
    }

    #[test]
    fn materialize_rule_with_support_dir_opencode_transforms_index_copies_support() {
        // OpenCode transforms the index (body + provenance); the support
        // dir is copied verbatim beside it so relative links resolve.
        let tmp = tempfile::tempdir().unwrap();
        let src = tmp.path().join("my-rule.md");
        std::fs::write(&src, "---\npaths: [\"a\"]\n---\n# index\n").unwrap();
        let support = tmp.path().join("my-rule");
        std::fs::create_dir_all(&support).unwrap();
        std::fs::write(support.join("examples.md"), "# ex\n").unwrap();

        let dest = tmp.path().join(".opencode/rules/my-rule.md");
        let files = ClientTarget::OpenCode
            .materialize(MaterializeRequest {
                kind: ArtifactKind::Rule,
                name: "my-rule",
                artifact_root: &src,
                dest: &dest,
                scope: ConfigScope::Project,
                pinned: "p",
                support_dir: Some(support.as_path()),
            })
            .unwrap();

        assert_eq!(files.iter().filter(|f| f.generated).count(), 1);
        let index = std::fs::read_to_string(&dest).unwrap();
        assert!(index.starts_with("<!-- generated by grim from p;"));
        assert!(!index.contains("paths:"));
        assert_eq!(
            std::fs::read_to_string(dest.parent().unwrap().join("my-rule/examples.md")).unwrap(),
            "# ex\n"
        );
    }

    #[test]
    fn materialize_skill_with_namespaced_metadata_renders_per_client() {
        let tmp = tempfile::tempdir().unwrap();
        let root = tmp.path().join("next");
        std::fs::create_dir_all(root.join("scripts")).unwrap();
        let canonical = "---\nname: next\ndescription: d\nmetadata:\n  keywords: a,b\n  claude.user-invocable: \"false\"\n---\n# body\n";
        std::fs::write(root.join("SKILL.md"), canonical).unwrap();
        std::fs::write(root.join("scripts/run.sh"), "echo hi\n").unwrap();

        for client in [
            ClientTarget::Claude,
            ClientTarget::OpenCode,
            ClientTarget::Copilot,
            ClientTarget::Codex,
        ] {
            let dest = tmp.path().join(format!("out-{client}/next"));
            let files = client
                .materialize(MaterializeRequest {
                    kind: ArtifactKind::Skill,
                    name: "next",
                    artifact_root: &root,
                    dest: &dest,
                    scope: ConfigScope::Project,
                    pinned: "p",
                    support_dir: None,
                })
                .unwrap();
            // The rendered index is generated; the sibling stays verbatim.
            let index = dest.join("SKILL.md");
            assert!(
                files.iter().any(|f| f.path == index && f.generated),
                "{client}: SKILL.md must be generated"
            );
            assert!(
                files
                    .iter()
                    .any(|f| f.path == dest.join("scripts/run.sh") && !f.generated),
                "{client}: siblings stay verbatim"
            );
            let doc = std::fs::read_to_string(&index).unwrap();
            assert!(
                !doc.contains("claude.user-invocable"),
                "{client}: namespaced key lifted/dropped"
            );
            assert!(doc.contains("keywords: a,b"), "{client}: plain metadata kept");
            if client == ClientTarget::Claude {
                assert!(doc.contains("user-invocable: false"), "native typed field for Claude");
            } else {
                assert!(!doc.contains("user-invocable"), "{client}: clean universal SKILL.md");
            }
        }
    }

    #[test]
    fn materialize_skill_without_namespaced_metadata_is_byte_identical() {
        let tmp = tempfile::tempdir().unwrap();
        let root = tmp.path().join("plain");
        std::fs::create_dir_all(&root).unwrap();
        let canonical = "---\nname: plain\ndescription: d\nmetadata:\n  keywords: a,b\n---\n# body\n";
        std::fs::write(root.join("SKILL.md"), canonical).unwrap();

        for client in [
            ClientTarget::Claude,
            ClientTarget::OpenCode,
            ClientTarget::Copilot,
            ClientTarget::Codex,
        ] {
            let dest = tmp.path().join(format!("out-{client}/plain"));
            let files = client
                .materialize(MaterializeRequest {
                    kind: ArtifactKind::Skill,
                    name: "plain",
                    artifact_root: &root,
                    dest: &dest,
                    scope: ConfigScope::Project,
                    pinned: "p",
                    support_dir: None,
                })
                .unwrap();
            assert!(files.iter().all(|f| !f.generated), "{client}: verbatim fast path");
            assert_eq!(
                std::fs::read_to_string(dest.join("SKILL.md")).unwrap(),
                canonical,
                "{client}: byte-identical install"
            );
        }
    }

    #[test]
    fn materialize_skill_rebound_binding_rewrites_frontmatter_name() {
        // Regression: a `--name` rebinding (binding ≠ frontmatter name)
        // must keep the Agent Skills directory-equality rule true at the
        // destination — the installed SKILL.md carries the binding as its
        // `name`, is marked generated, and every other key plus the body
        // survives. Siblings stay verbatim.
        let tmp = tempfile::tempdir().unwrap();
        let root = tmp.path().join("foo");
        std::fs::create_dir_all(root.join("scripts")).unwrap();
        std::fs::write(
            root.join("SKILL.md"),
            "---\nname: foo\ndescription: d\nmetadata:\n  keywords: a,b\n---\n# body\n",
        )
        .unwrap();
        std::fs::write(root.join("scripts/run.sh"), "echo hi\n").unwrap();

        for client in [ClientTarget::Claude, ClientTarget::OpenCode, ClientTarget::Copilot] {
            let dest = tmp.path().join(format!("out-{client}/bar"));
            let files = client
                .materialize(MaterializeRequest {
                    kind: ArtifactKind::Skill,
                    name: "bar",
                    artifact_root: &root,
                    dest: &dest,
                    scope: ConfigScope::Project,
                    pinned: "p",
                    support_dir: None,
                })
                .unwrap();
            let index = dest.join("SKILL.md");
            assert!(
                files.iter().any(|f| f.path == index && f.generated),
                "{client}: rebound SKILL.md must be generated"
            );
            let doc = std::fs::read_to_string(&index).unwrap();
            assert!(doc.contains("name: bar"), "{client}: name rewritten to binding: {doc}");
            assert!(!doc.contains("name: foo"), "{client}: stale name gone: {doc}");
            assert!(doc.contains("keywords: a,b"), "{client}: plain metadata kept: {doc}");
            assert!(doc.ends_with("# body\n"), "{client}: body preserved: {doc}");
            assert_eq!(
                std::fs::read_to_string(dest.join("scripts/run.sh")).unwrap(),
                "echo hi\n",
                "{client}: siblings stay verbatim"
            );
        }
    }

    #[test]
    fn materialize_rule_with_support_dir_copilot_transforms_index_copies_support() {
        // Copilot transforms only the index; the support dir is copied
        // verbatim beside it at `.github/instructions/<name>/`.
        let tmp = tempfile::tempdir().unwrap();
        let src = tmp.path().join("my-rule.md");
        std::fs::write(&src, "---\npaths: [\"a\"]\n---\n# index\nbody\n").unwrap();
        let support = tmp.path().join("my-rule");
        std::fs::create_dir_all(&support).unwrap();
        std::fs::write(support.join("examples.md"), "# ex\n").unwrap();

        let dest = tmp.path().join(".github/instructions/my-rule.instructions.md");
        let files = ClientTarget::Copilot
            .materialize(MaterializeRequest {
                kind: ArtifactKind::Rule,
                name: "my-rule",
                artifact_root: &src,
                dest: &dest,
                scope: ConfigScope::Project,
                pinned: "pin",
                support_dir: Some(support.as_path()),
            })
            .unwrap();

        // The index is the single generated file; support files are verbatim.
        assert_eq!(files.iter().filter(|f| f.generated).count(), 1);
        let index = std::fs::read_to_string(&dest).unwrap();
        assert!(index.starts_with("---\napplyTo: \"a\"\n---\n<!-- generated by grim from pin;"));
        assert!(!index.contains("paths:"), "canonical frontmatter mapped, not copied");
        let support_dest = dest.parent().unwrap().join("my-rule");
        assert_eq!(
            std::fs::read_to_string(support_dest.join("examples.md")).unwrap(),
            "# ex\n"
        );
    }

    /// A [`RootToken`] through the **real** HMAC derivation, keyed in a temp dir.
    ///
    /// No constructor exists and none should: minting one any other way is the
    /// forgeability the type deletes. `_tmp` is returned so the caller keeps the
    /// directory alive — dropping it would delete the key, which does not matter
    /// to a token already derived, but keeping the pair together makes the
    /// dependency visible.
    fn probe_root() -> (RootToken, tempfile::TempDir) {
        let tmp = tempfile::tempdir().unwrap();
        let token = super::super::hook_dispatch::root_token(tmp.path(), super::super::hook_dispatch::RootScope::Global)
            .expect("deriving a probe root token in a temp GRIM_HOME");
        (token, tmp)
    }

    #[test]
    fn hook_matrix_cell_declines_every_client_with_no_hook_surface() {
        // The fail-safe half of C-013. Quantified over `ALL` rather than a
        // literal list, so a new vendor is covered the day it lands.
        let (root, _tmp) = probe_root();
        let surfaceless: Vec<ClientTarget> = ClientTarget::ALL
            .into_iter()
            .filter(|client| client.vendor().hook_surface().is_none())
            .collect();
        assert_eq!(
            surfaceless.len(),
            15,
            "15 of 18 clients decline hooks outright; the roster moved: {surfaceless:?}"
        );
        for client in surfaceless {
            assert_eq!(
                hook_matrix_cell(client, &root),
                KindSupport::Declined,
                "client: {client:?}"
            );
        }
    }

    #[test]
    fn hook_matrix_cell_values_are_pinned_per_client() {
        // The whole shipped column, so WP-L's `clients.md` cell and this code
        // cannot drift apart silently, and so a projection-table edit that moves
        // a cell fails here rather than in a doc review.
        let (root, _tmp) = probe_root();
        for client in ClientTarget::ALL {
            let expected = match client {
                // Both host every declarable pair at every event they support.
                ClientTarget::Claude | ClientTarget::Codex => KindSupport::Native,
                // `verdict: &[]` at `PostToolUse`, where gatekeeper IS declarable
                // because claude and codex both block there — a projection-table
                // gap, matcher-independent, so it degrades the cell.
                ClientTarget::Copilot => KindSupport::Degraded,
                _ => KindSupport::Declined,
            };
            assert_eq!(hook_matrix_cell(client, &root), expected, "client: {client:?}");
        }
    }

    #[test]
    fn hook_cell_probe_independence() {
        // The cell is a documentation question, so it must not depend on a
        // resolved `$GRIM_HOME`. Two independently derived tokens (different
        // machine keys ⇒ different HMACs) must give the same column; if a future
        // refusal starts reading the root, this fails rather than the doc column
        // silently becoming environment-dependent. The launcher and table are
        // consts, so their independence is covered by the same argument — every
        // refusal returns before any of the three is read.
        let (first, _a) = probe_root();
        let (second, _b) = probe_root();
        assert_ne!(first, second, "two temp keys must derive different tokens");
        for client in ClientTarget::ALL {
            assert_eq!(
                hook_matrix_cell(client, &first),
                hook_matrix_cell(client, &second),
                "client: {client:?}"
            );
        }
    }

    #[test]
    fn hook_matrix_cell_is_not_hook_tier_support() {
        // S-013's silent guardrail, as an executable statement: for a mutator at
        // `PreToolUse` with a match-all matcher, the capability question answers
        // `Native` on claude and copilot while the REGISTRATION declines
        // (decision K — a match-all mutator could select a shell-command tool).
        // A cell filled from tier support alone would publish a mutator as
        // available where nothing is registered.
        let (root, _tmp) = probe_root();
        for client in [ClientTarget::Claude, ClientTarget::Copilot] {
            let vendor = client.vendor();
            assert_eq!(
                vendor.hook_tier_support(HookTier::Mutator, CanonicalEvent::PreToolUse),
                KindSupport::Native,
                "the capability question, {client:?}"
            );
            assert!(
                !hook_cell_probe_arms(vendor, CanonicalEvent::PreToolUse, HookTier::Mutator, None, &root),
                "but the match-all registration declines, {client:?}"
            );
            // And the any-arms quantifier is what keeps that per-matcher refusal
            // from moving the cell: the same tier arms for an exact, non-shell
            // tool name.
            assert!(
                hook_cell_probe_arms(
                    vendor,
                    CanonicalEvent::PreToolUse,
                    HookTier::Mutator,
                    Some("Read"),
                    &root
                ),
                "an exact non-shell matcher arms the same tier, {client:?}"
            );
        }
    }
}
