# SPDX-License-Identifier: Apache-2.0
# Copyright 2026 The Grimoire Authors
"""Goose and Kilo agent rendering (grimoire-rs/grimoire#147, #149).

- **Goose**: ``.goose/agents/<name>.md`` at project scope, ``~/.goose/agents/``
  globally — Goose's own directory, never the ``.agents/agents/`` Antigravity
  writes. Frontmatter ``name``/``description``/``model``; ``tools`` dropped
  with a warning.
- **Kilo**: ``.kilo/agents/<name>.md`` at project scope,
  ``$XDG_CONFIG_HOME/kilo/agents/`` globally — not the ``~/.kilo`` skills
  root. OpenCode's shape: no ``name``, no ``tools``, ``kilo.*`` lifted.
"""

from __future__ import annotations

import json
from pathlib import Path

from src.helpers import make_artifact, write_config
from src.registry import PublishedArtifact
from src.runner import GrimRunner


def _push(unique_repo: str, metadata: str = "") -> PublishedArtifact:
    meta = f"metadata:\n{metadata}" if metadata else ""
    doc = (
        "---\nname: rev\ndescription: Reviews code.\nmodel: sonnet\n"
        f"tools: Read, Grep\n{meta}---\n# rev\nbody\n"
    )
    return make_artifact(f"{unique_repo}/rev", "agent", {"rev.md": doc}, tag="v1")


def _install(runner, *args: str):
    result = runner.run("install", *args, format="json")
    return json.loads(result.stdout)["items"], result.stderr


def test_goose_agent_renders_to_its_own_dir_and_drops_tools_with_a_warning(
    grim_at, project_dir: Path, registry: str, unique_repo: str
) -> None:
    ag = _push(unique_repo)
    write_config(project_dir, agents={"rev": ag.fq})
    runner = grim_at(project_dir)
    runner.run("lock")

    rows, stderr = _install(runner, "--client", "goose")
    assert rows[0]["status"] == "installed", rows

    text = (project_dir / ".goose/agents/rev.md").read_text()
    assert text.startswith(
        "---\nname: rev\ndescription: Reviews code.\nmodel: sonnet\n---\n"
    ), text
    assert "tools" not in text, text
    assert "<!-- generated by grim from" in text
    assert "'tools'" in stderr and "goose" in stderr.lower(), stderr
    assert not (project_dir / ".agents/agents").exists(), (
        "Goose must never write the .agents/agents/ dir Antigravity owns"
    )


def test_kilo_agent_renders_opencode_shape_and_lifts_kilo_keys(
    grim_at, project_dir: Path, registry: str, unique_repo: str
) -> None:
    ag = _push(
        unique_repo,
        '  kilo.mode: subagent\n  kilo.temperature: "0.1"\n  opencode.mode: primary\n',
    )
    write_config(project_dir, agents={"rev": ag.fq})
    runner = grim_at(project_dir)
    runner.run("lock")

    rows, stderr = _install(runner, "--client", "kilo")
    assert rows[0]["status"] == "installed", rows

    text = (project_dir / ".kilo/agents/rev.md").read_text()
    assert "name:" not in text, "the filename is Kilo's agent identity"
    assert "tools" not in text, text
    assert "description: Reviews code.\n" in text
    assert "model: sonnet\n" in text
    assert "mode: subagent\n" in text and "primary" not in text, text
    assert "temperature: 0.1\n" in text
    assert "'tools'" in stderr and "kilo" in stderr.lower(), stderr


def test_reinstall_of_an_unchanged_agent_leaves_status_not_modified(
    grim_at, project_dir: Path, registry: str, unique_repo: str
) -> None:
    """Self-heal: the render is deterministic, so a second install is a no-op
    and ``status`` reads ``installed`` with nothing pending."""
    ag = _push(unique_repo, "  kilo.mode: subagent\n")
    cfg = write_config(project_dir, agents={"rev": ag.fq})
    cfg.write_text(cfg.read_text() + '\n[options]\nclients = ["goose", "kilo"]\n')
    runner = grim_at(project_dir)
    runner.run("lock")
    _install(runner)
    before = {
        p: p.read_bytes()
        for p in (
            project_dir / ".goose/agents/rev.md",
            project_dir / ".kilo/agents/rev.md",
        )
    }

    rows, _ = _install(runner)
    assert all(r["status"] != "installed" for r in rows), (
        f"second install must be a no-op: {rows}"
    )
    for path, data in before.items():
        assert path.read_bytes() == data, path

    row = runner.json("status")["items"][0]
    assert row["state"] == "installed", row
    assert row["outputs_pending"] == [], row
    assert {o["client"] for o in row["outputs"]} == {"goose", "kilo"}, row


def test_agent_installed_before_goose_was_supported_shows_as_pending(
    grim_at, project_dir: Path, registry: str, unique_repo: str
) -> None:
    """The kind flip's upgrade path: an install that recorded no Goose output
    (as a Goose-declining grim did) is pending work for ``status`` and
    ``install`` writes it."""
    ag = _push(unique_repo)
    write_config(project_dir, agents={"rev": ag.fq})
    (project_dir / ".claude").mkdir(exist_ok=True)
    (project_dir / ".goose").mkdir()
    runner = grim_at(project_dir)
    runner.run("lock")
    _install(runner, "--client", "claude")

    row = runner.json("status")["items"][0]
    assert row["state"] == "installed", row
    assert {o["client"] for o in row["outputs_pending"]} == {"goose"}, row

    runner.run("install")
    assert (project_dir / ".goose/agents/rev.md").is_file()
    assert runner.json("status")["items"][0]["outputs_pending"] == []


def test_global_goose_agent_lands_in_home_dot_goose(
    grim_binary: Path, grim_home: Path, registry: str, unique_repo: str
) -> None:
    ag = _push(unique_repo)
    (grim_home / "grimoire.toml").write_text(f'[agents]\nrev = "{ag.fq}"\n')
    runner = GrimRunner(grim_binary, grim_home)
    # $GOOSE_PATH_ROOT relocates Goose's config dir, not its agents.
    runner.env["GOOSE_PATH_ROOT"] = str(grim_home.parent / "goose-root")
    runner.json("lock", "--global")

    runner.run("install", "--global", "--client", "goose", format="json")

    assert (runner.home / ".goose/agents/rev.md").is_file()
    assert not (grim_home.parent / "goose-root").exists()
    assert runner.json("status", "--global")["items"][0]["state"] == "installed"


def test_global_kilo_agent_follows_xdg_config_home_not_the_kilo_skills_root(
    grim_binary: Path, grim_home: Path, registry: str, unique_repo: str
) -> None:
    ag = _push(unique_repo)
    (grim_home / "grimoire.toml").write_text(f'[agents]\nrev = "{ag.fq}"\n')
    runner = GrimRunner(grim_binary, grim_home)
    xdg = grim_home.parent / "custom-xdg-kilo"
    runner.env["XDG_CONFIG_HOME"] = str(xdg)
    runner.json("lock", "--global")

    runner.run("install", "--global", "--client", "kilo", format="json")

    assert (xdg / "kilo/agents/rev.md").is_file()
    assert not (runner.home / ".kilo/agents").exists(), (
        "agents never go to the ~/.kilo skills root"
    )
    assert not (runner.home / ".config/kilo/agents").exists()
    row = runner.json("status", "--global")["items"][0]
    assert row["state"] == "installed", row

    out = runner.json("uninstall", "--global", "agent", "rev")
    assert out["status"] in ("uninstalled", "removed"), out
    assert not (xdg / "kilo/agents/rev.md").exists()
