# SPDX-License-Identifier: Apache-2.0
# Copyright 2026 The Grimoire Authors
"""`grim install --target` multi-editor acceptance tests."""
from __future__ import annotations

from pathlib import Path

from src.assertions import assert_path_exists
from src.helpers import make_artifact, write_config


def _setup(project_dir: Path, unique_repo: str):
    sk = make_artifact(
        f"{unique_repo}/code-review",
        "skill",
        {
            "code-review/SKILL.md": "---\nname: code-review\ndescription: d\n---\n# CR\n",
            "code-review/scripts/run.sh": "echo hi\n",
        },
        tag="stable",
    )
    ru = make_artifact(
        f"{unique_repo}/rust-style",
        "rule",
        {"rust-style.md": "---\npaths: ['**/*.rs']\n---\n# Rust Style\nUse 4 spaces.\n"},
        tag="v1",
    )
    write_config(
        project_dir,
        skills={"code-review": sk.fq},
        rules={"rust-style": ru.fq},
    )
    return sk, ru


def test_install_claude_and_copilot_layouts(
    grim_at, project_dir: Path, registry: str, unique_repo: str
) -> None:
    _setup(project_dir, unique_repo)
    runner = grim_at(project_dir)
    runner.run("lock", check=False)

    rows = runner.json("install", "--target", "claude,copilot")
    assert {r["status"] for r in rows} == {"installed"}

    # Claude: canonical skill + rule.
    assert_path_exists(project_dir / ".claude/skills/code-review/SKILL.md")
    assert_path_exists(
        project_dir / ".claude/skills/code-review/scripts/run.sh"
    )
    assert_path_exists(project_dir / ".claude/rules/rust-style.md")

    # Copilot: canonical skill, transformed rule.
    assert_path_exists(project_dir / ".github/skills/code-review/SKILL.md")
    instr = project_dir / ".github/instructions/rust-style.instructions.md"
    assert_path_exists(instr)
    body = instr.read_text()
    assert body.startswith("<!-- generated by grim from "), (
        f"copilot instructions must carry a provenance header, got: {body!r}"
    )
    assert "edits will be overwritten -->" in body.splitlines()[0]
    assert "paths:" not in body, (
        "the `paths:` frontmatter must be stripped from the transform"
    )
    assert "Use 4 spaces." in body


def test_editing_generated_copilot_file_is_detected_as_drift(
    grim_at, project_dir: Path, registry: str, unique_repo: str
) -> None:
    _setup(project_dir, unique_repo)
    runner = grim_at(project_dir)
    runner.run("lock", check=False)
    runner.run("install", "--target", "copilot", check=False)

    instr = project_dir / ".github/instructions/rust-style.instructions.md"
    instr.write_text("hand edited by a user\n")

    # The integrity hash for a generated file is over its *expected*
    # bytes, so a user edit is detected exactly like a canonical file.
    rows = runner.json("status")
    rule_row = next(r for r in rows if r["name"] == "rust-style")
    assert rule_row["state"] == "modified", (
        f"editing a generated copilot file must report modified, got "
        f"{rule_row}"
    )

    # A plain `install` (no --force) refuses the generated-file drift.
    refused = runner.run("install", "--target", "copilot", check=False)
    assert refused.returncode == 65, (
        f"install without --force must refuse generated-file drift (65), "
        f"got {refused.returncode}; {refused.stderr}"
    )
    assert instr.read_text() == "hand edited by a user\n", (
        "a refused install must not overwrite the user's edit"
    )

    # `--force` regenerates the deterministic transform output.
    forced = runner.run("install", "--target", "copilot", "--force", check=False)
    assert forced.returncode == 0, (
        f"forced install must succeed, got {forced.returncode}; "
        f"{forced.stderr}"
    )
    assert instr.read_text().startswith("<!-- generated by grim from ")


def test_copilot_regeneration_is_idempotent(
    grim_at, project_dir: Path, registry: str, unique_repo: str
) -> None:
    _setup(project_dir, unique_repo)
    runner = grim_at(project_dir)
    runner.run("lock", check=False)
    runner.run("install", "--target", "copilot", check=False)
    instr = project_dir / ".github/instructions/rust-style.instructions.md"
    first = instr.read_text()

    # A second install over intact content is a no-op; the bytes are
    # byte-identical (deterministic transform).
    runner.run("install", "--target", "copilot", check=False)
    assert instr.read_text() == first
